insert into Practica1 (nombre, palabraSecreta) values ('Brandtr Pawfoot', 'Inverse');
insert into Practica1 (nombre, palabraSecreta) values ('Emmanuel Sofe', 'core');
insert into Practica1 (nombre, palabraSecreta) values ('Mychal Gainor', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Aldin Lambol', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Stacee Peppett', 'Synchronised');
insert into Practica1 (nombre, palabraSecreta) values ('Vittorio Bowker', 'Multi-tiered');
insert into Practica1 (nombre, palabraSecreta) values ('Denice Belchambers', 'flexibility');
insert into Practica1 (nombre, palabraSecreta) values ('Cyndie Jado', '3rd generation');
insert into Practica1 (nombre, palabraSecreta) values ('Edith Khomin', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Filberte Hobgen', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Deloris MacConnell', 'application');
insert into Practica1 (nombre, palabraSecreta) values ('Gusella Ameer-Beg', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Jennine McTrustam', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Sadie Rowesby', 'project');
insert into Practica1 (nombre, palabraSecreta) values ('Charisse Windress', 'Enterprise-wide');
insert into Practica1 (nombre, palabraSecreta) values ('Dianna Farrance', 'responsive');
insert into Practica1 (nombre, palabraSecreta) values ('Stewart Espy', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Pam Wyon', 'Face to face');
insert into Practica1 (nombre, palabraSecreta) values ('Elliott Sprigg', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Torr Haughin', 'open system');
insert into Practica1 (nombre, palabraSecreta) values ('Roanna Cromie', 'encryption');
insert into Practica1 (nombre, palabraSecreta) values ('Melva Winscom', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Bartlett Francillo', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Lonnie Dinwoodie', 'Configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Godfry Ibeson', 'Vision-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Kenon McCane', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Iago Geall', 'static');
insert into Practica1 (nombre, palabraSecreta) values ('Katrine Ebbitt', 'optimal');
insert into Practica1 (nombre, palabraSecreta) values ('Ange Shallo', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Tedman Offen', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Drucy Lettson', 'Front-line');
insert into Practica1 (nombre, palabraSecreta) values ('Hurlee Osgordby', 'knowledge user');
insert into Practica1 (nombre, palabraSecreta) values ('Molly Stapleford', 'Open-architected');
insert into Practica1 (nombre, palabraSecreta) values ('Peder Bordis', 'intranet');
insert into Practica1 (nombre, palabraSecreta) values ('Corbie Revey', 'high-level');
insert into Practica1 (nombre, palabraSecreta) values ('Austina Dobrowolny', 'bifurcated');
insert into Practica1 (nombre, palabraSecreta) values ('Lauretta Burston', 'disintermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Lamond Marzelle', 'demand-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Mindy Ong', 'circuit');
insert into Practica1 (nombre, palabraSecreta) values ('Jerrie Hembrow', 'Extended');
insert into Practica1 (nombre, palabraSecreta) values ('Gillan Doyle', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Justine Dearle', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Gerik Buddock', 'Diverse');
insert into Practica1 (nombre, palabraSecreta) values ('Dotti Kunkler', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Wileen Easter', 'regional');
insert into Practica1 (nombre, palabraSecreta) values ('Menard Ashbee', 'Pre-emptive');
insert into Practica1 (nombre, palabraSecreta) values ('Evelina Boultwood', 'Multi-tiered');
insert into Practica1 (nombre, palabraSecreta) values ('Odille Wallage', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Oralie Brownsea', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Wileen Matushevich', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Lebbie Riditch', 'eco-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Loree Longmire', 'artificial intelligence');
insert into Practica1 (nombre, palabraSecreta) values ('Becka Hamber', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Roxana Westrope', 'support');
insert into Practica1 (nombre, palabraSecreta) values ('Helga De Banke', 'standardization');
insert into Practica1 (nombre, palabraSecreta) values ('Shea Stoving', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Orin Rookesby', '24/7');
insert into Practica1 (nombre, palabraSecreta) values ('Marie-ann Langeren', 'Mandatory');
insert into Practica1 (nombre, palabraSecreta) values ('Reuven Stickley', 'Automated');
insert into Practica1 (nombre, palabraSecreta) values ('Valeria Buckler', '3rd generation');
insert into Practica1 (nombre, palabraSecreta) values ('Veradis Castelow', 'Horizontal');
insert into Practica1 (nombre, palabraSecreta) values ('Cecile Keslake', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Annadiana Cescot', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Sawyer Ashlin', 'neutral');
insert into Practica1 (nombre, palabraSecreta) values ('Robena Dennidge', 'groupware');
insert into Practica1 (nombre, palabraSecreta) values ('Daron Maffezzoli', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Hernando Godfrey', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Cassondra Scarff', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Rhody Gilgryst', 'time-frame');
insert into Practica1 (nombre, palabraSecreta) values ('Melony Parfitt', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Ozzie Greves', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Gwen Naisbitt', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Standford Insole', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Christophe Cornilli', 'Object-based');
insert into Practica1 (nombre, palabraSecreta) values ('Doe Maccrae', 'open system');
insert into Practica1 (nombre, palabraSecreta) values ('Talya Simoncelli', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Albertine Adshed', 'productivity');
insert into Practica1 (nombre, palabraSecreta) values ('Michelle Kloss', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Ardelis Geockle', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Aila Balfe', 'structure');
insert into Practica1 (nombre, palabraSecreta) values ('Spence Lehenmann', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Gerry Mettrick', 'definition');
insert into Practica1 (nombre, palabraSecreta) values ('Carroll Lutwidge', 'monitoring');
insert into Practica1 (nombre, palabraSecreta) values ('Ardys Penson', 'Open-source');
insert into Practica1 (nombre, palabraSecreta) values ('Judie Husbands', 'success');
insert into Practica1 (nombre, palabraSecreta) values ('Neda Brome', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Millard Grundell', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Martie Teasdale-Markie', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Falito Chipps', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Vanya Piggrem', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Annice Hastler', 'Extended');
insert into Practica1 (nombre, palabraSecreta) values ('Bree Salmen', 'mission-critical');
insert into Practica1 (nombre, palabraSecreta) values ('Alicia Deverson', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Domingo Leile', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Lurleen Dumbell', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Felix Dominici', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Flory Akett', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Loralee Leechman', 'asymmetric');
insert into Practica1 (nombre, palabraSecreta) values ('Darnell Terbeek', 'website');
insert into Practica1 (nombre, palabraSecreta) values ('Meghan Driver', 'Synchronised');
insert into Practica1 (nombre, palabraSecreta) values ('Hamil Napolione', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Rosemaria Dary', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Sheilah Forstall', 'empowering');
insert into Practica1 (nombre, palabraSecreta) values ('Lester Gianulli', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Kimbell Rumble', 'Open-source');
insert into Practica1 (nombre, palabraSecreta) values ('Timothea Bentham', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Eolande Siddon', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Lurleen Riordan', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Danyelle Simkovitz', 'support');
insert into Practica1 (nombre, palabraSecreta) values ('Lynnet Burgise', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Milton Phinnis', 'dynamic');
insert into Practica1 (nombre, palabraSecreta) values ('Broderick Gilstin', 'reciprocal');
insert into Practica1 (nombre, palabraSecreta) values ('Alvera Preble', 'neutral');
insert into Practica1 (nombre, palabraSecreta) values ('Reggie Curwen', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Ethelyn Press', 'attitude-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Lizzy Silburn', 'demand-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Nita Macilhench', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Karla Sarge', 'empowering');
insert into Practica1 (nombre, palabraSecreta) values ('Edy Michele', 'Open-architected');
insert into Practica1 (nombre, palabraSecreta) values ('Herby Kensett', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Ermengarde Bennellick', 'Object-based');
insert into Practica1 (nombre, palabraSecreta) values ('Hedvig Snelgar', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Babb Varnals', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Janka Sarge', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Kitty Unger', 'Object-based');
insert into Practica1 (nombre, palabraSecreta) values ('Florette Ruscoe', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Daria Glassford', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Charo McCurlye', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Gratiana De Freyne', 'Innovative');
insert into Practica1 (nombre, palabraSecreta) values ('Kristina Goodier', 'Secured');
insert into Practica1 (nombre, palabraSecreta) values ('Richmound Morriss', 'utilisation');
insert into Practica1 (nombre, palabraSecreta) values ('Brit Brownsell', 'local');
insert into Practica1 (nombre, palabraSecreta) values ('Jozef Ivantyev', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Tracie Alliband', 'reciprocal');
insert into Practica1 (nombre, palabraSecreta) values ('Leonore Folley', 'structure');
insert into Practica1 (nombre, palabraSecreta) values ('Ludovico Cookes', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Nathaniel Harnetty', 'optimal');
insert into Practica1 (nombre, palabraSecreta) values ('Colas Pol', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Lindsy Geall', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Oswald Louthe', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Oberon Carberry', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Evie Rego', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Johannah Beaton', 'workforce');
insert into Practica1 (nombre, palabraSecreta) values ('Zaccaria Burless', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Amble Burree', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Donn Logie', 'background');
insert into Practica1 (nombre, palabraSecreta) values ('Maridel Scrooby', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Cozmo Aberchirder', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Sibel Izhaky', 'conglomeration');
insert into Practica1 (nombre, palabraSecreta) values ('Gustaf Webling', 'conglomeration');
insert into Practica1 (nombre, palabraSecreta) values ('Corbin Deighton', 'Face to face');
insert into Practica1 (nombre, palabraSecreta) values ('Josh Leedal', 'portal');
insert into Practica1 (nombre, palabraSecreta) values ('Bernadette Pickton', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Lebbie Ower', 'Extended');
insert into Practica1 (nombre, palabraSecreta) values ('Willey Bonafacino', 'asymmetric');
insert into Practica1 (nombre, palabraSecreta) values ('Taffy Espinas', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Georgie Glauber', 'multi-tasking');
insert into Practica1 (nombre, palabraSecreta) values ('Kristel Titcom', 'encoding');
insert into Practica1 (nombre, palabraSecreta) values ('Tallie Ellse', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Quentin Eirwin', 'knowledge base');
insert into Practica1 (nombre, palabraSecreta) values ('Calley Matzeitis', 'responsive');
insert into Practica1 (nombre, palabraSecreta) values ('Kamillah Fullbrook', 'Object-based');
insert into Practica1 (nombre, palabraSecreta) values ('Prescott Adcock', 'Cross-group');
insert into Practica1 (nombre, palabraSecreta) values ('Cristine Inseal', 'Secured');
insert into Practica1 (nombre, palabraSecreta) values ('Tobe Comettoi', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Stesha Crain', 'demand-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Benjamen Parkhouse', 'real-time');
insert into Practica1 (nombre, palabraSecreta) values ('Angela Dixey', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Dukie Jeacocke', 'Assimilated');
insert into Practica1 (nombre, palabraSecreta) values ('Obadias McGrudder', 'matrices');
insert into Practica1 (nombre, palabraSecreta) values ('Weber Coram', 'Focused');
insert into Practica1 (nombre, palabraSecreta) values ('Rozamond Baggally', 'architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Blayne McNab', 'heuristic');
insert into Practica1 (nombre, palabraSecreta) values ('Gianni Ivic', 'system-worthy');
insert into Practica1 (nombre, palabraSecreta) values ('Ashlee Wordsworth', 'system-worthy');
insert into Practica1 (nombre, palabraSecreta) values ('Fanechka Fountain', 'Inverse');
insert into Practica1 (nombre, palabraSecreta) values ('Rafaellle Wiper', 'monitoring');
insert into Practica1 (nombre, palabraSecreta) values ('Bobbee Baume', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Pierrette Melior', 'multi-tasking');
insert into Practica1 (nombre, palabraSecreta) values ('Trudi Lyptrit', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Zack Senn', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Amity Shimuk', 'instruction set');
insert into Practica1 (nombre, palabraSecreta) values ('Randy Ronayne', 'object-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Ailyn Eslemont', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Mellisa Mocher', 'De-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Gannon Gingles', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Gwenneth Cordet', 'explicit');
insert into Practica1 (nombre, palabraSecreta) values ('Burty Varnam', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Conrade Conrart', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Ermina Mellodey', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Saunders Dunbleton', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Kaine Forson', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Ignatius Edmons', 'even-keeled');
insert into Practica1 (nombre, palabraSecreta) values ('Roddy Foster-Smith', 'Graphic Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Aurora Kerrigan', 'Synergistic');
insert into Practica1 (nombre, palabraSecreta) values ('Muriel Marnane', 'utilisation');
insert into Practica1 (nombre, palabraSecreta) values ('Eddy Garlee', 'Upgradable');
insert into Practica1 (nombre, palabraSecreta) values ('Frankie Willden', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Toiboid Izzatt', 'bi-directional');
insert into Practica1 (nombre, palabraSecreta) values ('Manny Ludovico', 'help-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Luisa Noel', 'Implemented');
insert into Practica1 (nombre, palabraSecreta) values ('Nathalie Harman', 'Focused');
insert into Practica1 (nombre, palabraSecreta) values ('Tobe Cumberpatch', 'mobile');
insert into Practica1 (nombre, palabraSecreta) values ('Augusto McCaughan', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Nolie Kinig', 'artificial intelligence');
insert into Practica1 (nombre, palabraSecreta) values ('Tobias O''Scanlan', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Billie Durnall', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Gerrie Pendrid', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Melanie Tettley', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Camille Spenclay', 'Implemented');
insert into Practica1 (nombre, palabraSecreta) values ('Walsh Sussex', 'User-friendly');
insert into Practica1 (nombre, palabraSecreta) values ('Neddie Ivanin', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Hube Heelis', 'definition');
insert into Practica1 (nombre, palabraSecreta) values ('Donalt Sikorsky', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Brennen Simonutti', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Genia Legrice', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Garwin Andover', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Barri Giraudel', 'data-warehouse');
insert into Practica1 (nombre, palabraSecreta) values ('Fifine Sadlier', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Malory Batstone', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Cortie Symonds', 'dynamic');
insert into Practica1 (nombre, palabraSecreta) values ('Sheffie Saywell', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Glen Marishenko', 'circuit');
insert into Practica1 (nombre, palabraSecreta) values ('Nan Vaugham', 'encoding');
insert into Practica1 (nombre, palabraSecreta) values ('Terrel Lyster', 'Programmable');
insert into Practica1 (nombre, palabraSecreta) values ('Irwinn McCooke', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Hedwiga Mogenot', 'grid-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Penny Dagger', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Jilli Goodfellow', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Si Brambill', 'moderator');
insert into Practica1 (nombre, palabraSecreta) values ('Iormina Tybalt', 'fault-tolerant');
insert into Practica1 (nombre, palabraSecreta) values ('Teresa Godfree', 'Adaptive');
insert into Practica1 (nombre, palabraSecreta) values ('Neile Del Castello', 'solution-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Galina Le Friec', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Avie Hexum', 'website');
insert into Practica1 (nombre, palabraSecreta) values ('Carmencita Godrich', 'Synergized');
insert into Practica1 (nombre, palabraSecreta) values ('Kellen Dast', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Gary Bruneton', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Fiann MacGillespie', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Donielle Danton', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Suki Castenda', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Hercules Mulrean', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Ferdie Hender', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Eada Bruckman', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Cassi Schofield', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Dehlia Cusworth', 'focus group');
insert into Practica1 (nombre, palabraSecreta) values ('Jaime Nanson', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Karry Mintoft', 'Reactive');
insert into Practica1 (nombre, palabraSecreta) values ('Raymond Keane', '5th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Perry Pughsley', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Desiree Flaxman', 'installation');
insert into Practica1 (nombre, palabraSecreta) values ('Ulysses Critoph', 'solution');
insert into Practica1 (nombre, palabraSecreta) values ('Shellysheldon Dyball', 'background');
insert into Practica1 (nombre, palabraSecreta) values ('Kristin Fearfull', 'Sharable');
insert into Practica1 (nombre, palabraSecreta) values ('Orion Corstan', 'Synergized');
insert into Practica1 (nombre, palabraSecreta) values ('Zacharias Gothard', 'foreground');
insert into Practica1 (nombre, palabraSecreta) values ('Gretal Hastler', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Stefanie Brownsall', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Eirena Kinchley', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Selena Humes', 'composite');
insert into Practica1 (nombre, palabraSecreta) values ('Kimmi Fawks', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Elisha Filliskirk', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Ronnie Exeter', 'stable');
insert into Practica1 (nombre, palabraSecreta) values ('Eldin Szymonwicz', 'system engine');
insert into Practica1 (nombre, palabraSecreta) values ('Evy Hugett', 'Upgradable');
insert into Practica1 (nombre, palabraSecreta) values ('Henryetta Buckwell', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Karalynn Foresight', 'secondary');
insert into Practica1 (nombre, palabraSecreta) values ('Druci Nassie', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Francene Hardage', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Orel MacCleod', 'encoding');
insert into Practica1 (nombre, palabraSecreta) values ('Ammamaria Cobbold', 'interface');
insert into Practica1 (nombre, palabraSecreta) values ('Codie Castro', 'data-warehouse');
insert into Practica1 (nombre, palabraSecreta) values ('Cicely Prestidge', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Giffer Athowe', 'superstructure');
insert into Practica1 (nombre, palabraSecreta) values ('Lezlie Enric', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Doralin Apark', '5th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Guinevere Koch', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Wat O''Hogertie', 'web-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Otha Flatt', 'encoding');
insert into Practica1 (nombre, palabraSecreta) values ('Vere Ninotti', 'artificial intelligence');
insert into Practica1 (nombre, palabraSecreta) values ('Mahala Battelle', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Nertie Romney', 'even-keeled');
insert into Practica1 (nombre, palabraSecreta) values ('Glyn Scuffham', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Maddy Carverhill', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Ronald Macura', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Wheeler Scedall', 'asynchronous');
insert into Practica1 (nombre, palabraSecreta) values ('Karina Lawler', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Deeann Yoodall', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Marylinda Sigfrid', 'dynamic');
insert into Practica1 (nombre, palabraSecreta) values ('Hannis Newman', 'Configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Mil Faye', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Clevey Ceeley', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Lauritz Whorton', 'Organized');
insert into Practica1 (nombre, palabraSecreta) values ('Emiline Mathieson', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Adah Hayesman', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Ezmeralda Malam', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Cale Kobierra', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Blake Gregoratti', 'Adaptive');
insert into Practica1 (nombre, palabraSecreta) values ('Sayre Dowle', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Keene Kruger', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Kessiah Chalcraft', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Garvy Faulder', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Kipp Whifen', 'composite');
insert into Practica1 (nombre, palabraSecreta) values ('Erinna Dungate', 'reciprocal');
insert into Practica1 (nombre, palabraSecreta) values ('Lisabeth Kenneford', 'paradigm');
insert into Practica1 (nombre, palabraSecreta) values ('Abby Janssens', 'disintermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Shadow Worsalls', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Bernadene Guiden', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Saree Pavlenkov', 'throughput');
insert into Practica1 (nombre, palabraSecreta) values ('Ethan MacGilpatrick', 'next generation');
insert into Practica1 (nombre, palabraSecreta) values ('Ketti Rowley', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Glynnis Scorton', 'Programmable');
insert into Practica1 (nombre, palabraSecreta) values ('Ann-marie Mathet', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Gracie Biesterfeld', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Berke Wheway', 'Open-source');
insert into Practica1 (nombre, palabraSecreta) values ('Beckie Waddington', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Barn Coffey', 'definition');
insert into Practica1 (nombre, palabraSecreta) values ('Alf Helis', 'Grass-roots');
insert into Practica1 (nombre, palabraSecreta) values ('Brandy Coddington', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Ewan Celand', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Colman Keepe', 'Automated');
insert into Practica1 (nombre, palabraSecreta) values ('Corey Crocket', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Leighton Matiewe', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Rachel Ashbridge', 'Upgradable');
insert into Practica1 (nombre, palabraSecreta) values ('Verna Blindmann', 'even-keeled');
insert into Practica1 (nombre, palabraSecreta) values ('Koralle Becom', 'stable');
insert into Practica1 (nombre, palabraSecreta) values ('Fabian Discombe', 'optimal');
insert into Practica1 (nombre, palabraSecreta) values ('Nevil Croutear', 'artificial intelligence');
insert into Practica1 (nombre, palabraSecreta) values ('Zorine Wynes', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Dyana Gaiford', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Mandel Frisel', 'hub');
insert into Practica1 (nombre, palabraSecreta) values ('Sawyere Dowsey', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Adena Alejandri', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Dillon Liven', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Graham Le Marchand', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Lesli Tolworthie', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Gwenneth Taillard', 'time-frame');
insert into Practica1 (nombre, palabraSecreta) values ('Beilul Goodacre', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Eloisa Demko', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Ninette Sandford', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Belinda Iacopetti', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Fayth Dillinger', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Carri Ferenczy', 'productivity');
insert into Practica1 (nombre, palabraSecreta) values ('Arluene Trownson', 'structure');
insert into Practica1 (nombre, palabraSecreta) values ('Broderick Tunnah', 'open system');
insert into Practica1 (nombre, palabraSecreta) values ('Bertrand Neller', 'help-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Orton Albertson', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Maynord Huey', 'website');
insert into Practica1 (nombre, palabraSecreta) values ('Roxine Baron', 'context-sensitive');
insert into Practica1 (nombre, palabraSecreta) values ('Giovanna Blaase', 'Pre-emptive');
insert into Practica1 (nombre, palabraSecreta) values ('Shanan Hutten', '5th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Chaddy Beadnall', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Guilbert Rundall', 'productivity');
insert into Practica1 (nombre, palabraSecreta) values ('Anderson Josebury', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Dick Broscombe', 'system-worthy');
insert into Practica1 (nombre, palabraSecreta) values ('Wolfie Aitcheson', 'website');
insert into Practica1 (nombre, palabraSecreta) values ('Diandra Behning', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Reinhard Yuille', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Elmore Errett', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Anna-diane Kollach', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Cortney Yellowlees', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Seymour Cushworth', 'dedicated');
insert into Practica1 (nombre, palabraSecreta) values ('Rubie Baylay', 'moratorium');
insert into Practica1 (nombre, palabraSecreta) values ('Ogdan Lamping', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Elna Morales', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Fleming O''Carney', 'secondary');
insert into Practica1 (nombre, palabraSecreta) values ('Theadora Hargrove', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Nady Collie', 'User-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Tucker O''Duane', 'Mandatory');
insert into Practica1 (nombre, palabraSecreta) values ('Sofia Du Hamel', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Danie Creese', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Sayers Rodgman', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Ambur Farnan', 'Virtual');
insert into Practica1 (nombre, palabraSecreta) values ('Elinor McCreadie', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Jordan Pymm', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Tori Endle', 'multimedia');
insert into Practica1 (nombre, palabraSecreta) values ('Jsandye Kisbey', 'knowledge base');
insert into Practica1 (nombre, palabraSecreta) values ('Tildie Steart', 'Right-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Waite Skyrm', 'Implemented');
insert into Practica1 (nombre, palabraSecreta) values ('Giana Boanas', 'tertiary');
insert into Practica1 (nombre, palabraSecreta) values ('Dareen Moro', 'mission-critical');
insert into Practica1 (nombre, palabraSecreta) values ('Trude Goodright', 'open architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Bent O''Rafferty', 'Intuitive');
insert into Practica1 (nombre, palabraSecreta) values ('Chalmers McCaffery', 'impactful');
insert into Practica1 (nombre, palabraSecreta) values ('Hashim Myrick', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Diann Tawton', 'encoding');
insert into Practica1 (nombre, palabraSecreta) values ('Germain Quennell', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Aron Balentyne', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Bobette Fontaine', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Madelyn Blowfelde', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Angeli Snelle', 'Cloned');
insert into Practica1 (nombre, palabraSecreta) values ('Karly Meijer', 'explicit');
insert into Practica1 (nombre, palabraSecreta) values ('Sunny Shugg', '3rd generation');
insert into Practica1 (nombre, palabraSecreta) values ('Miner Vooght', 'optimal');
insert into Practica1 (nombre, palabraSecreta) values ('Donna Cropton', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Cornelia Pinyon', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Walther Duckham', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Findley Bartkiewicz', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Carling Ellerton', 'standardization');
insert into Practica1 (nombre, palabraSecreta) values ('Lonny Jepps', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Dill Cord', 'project');
insert into Practica1 (nombre, palabraSecreta) values ('Fleurette Stather', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Benedikt Stampe', 'Balanced');
insert into Practica1 (nombre, palabraSecreta) values ('Marj Vian', 'Fully-configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Blanch Corrigan', 'Multi-tiered');
insert into Practica1 (nombre, palabraSecreta) values ('Tymothy Backes', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Byrann Edlington', 'actuating');
insert into Practica1 (nombre, palabraSecreta) values ('Dolli Titterington', 'structure');
insert into Practica1 (nombre, palabraSecreta) values ('Binky Mattea', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Bili Dubble', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Blakelee Riolfo', 'Mandatory');
insert into Practica1 (nombre, palabraSecreta) values ('Sallie La Croce', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Fan Parsonage', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Noelani MacNeil', 'Adaptive');
insert into Practica1 (nombre, palabraSecreta) values ('Manuel Kubis', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Cletis D''Antoni', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Rachael Winspur', 'regional');
insert into Practica1 (nombre, palabraSecreta) values ('Benny Volker', 'attitude-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Myrtle Wilsey', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Erma Teck', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Chantalle Ricciardello', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Sephira Aherne', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Merci Couch', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Fritz Annott', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Ardisj Briton', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Crissy Andryushchenko', 'installation');
insert into Practica1 (nombre, palabraSecreta) values ('Sallyann Dwire', 'Synchronised');
insert into Practica1 (nombre, palabraSecreta) values ('Sapphira Lowther', 'needs-based');
insert into Practica1 (nombre, palabraSecreta) values ('Jonathan MacQuarrie', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Noelyn Blacker', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Tommie Dubose', 'knowledge user');
insert into Practica1 (nombre, palabraSecreta) values ('Shirleen Le Pine', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Lisette Howlin', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Sara Paffitt', 'model');
insert into Practica1 (nombre, palabraSecreta) values ('Arlee Skellern', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Corrine Sinfield', 'data-warehouse');
insert into Practica1 (nombre, palabraSecreta) values ('Caryl Culp', 'frame');
insert into Practica1 (nombre, palabraSecreta) values ('Tallia Dabnot', 'flexibility');
insert into Practica1 (nombre, palabraSecreta) values ('Rockwell Ovell', 'Organic');
insert into Practica1 (nombre, palabraSecreta) values ('Syd Cosely', 'secondary');
insert into Practica1 (nombre, palabraSecreta) values ('Starr Bloomfield', 'high-level');
insert into Practica1 (nombre, palabraSecreta) values ('Mata Lockett', 'empowering');
insert into Practica1 (nombre, palabraSecreta) values ('Charmane Wortley', 'web-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Wilek Rosenvasser', 'moderator');
insert into Practica1 (nombre, palabraSecreta) values ('Melinda Garrard', 'matrices');
insert into Practica1 (nombre, palabraSecreta) values ('Milton Kitt', 'foreground');
insert into Practica1 (nombre, palabraSecreta) values ('Marcille Jenson', 'Ameliorated');
insert into Practica1 (nombre, palabraSecreta) values ('Shurlock Ebden', 'adapter');
insert into Practica1 (nombre, palabraSecreta) values ('Aline Danit', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Robinet Brimfield', 'structure');
insert into Practica1 (nombre, palabraSecreta) values ('Cordy Grimsdyke', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Kimble McCallam', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Mureil Smallsman', 'help-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Lucy Spary', 'systemic');
insert into Practica1 (nombre, palabraSecreta) values ('Talbot Everill', 'human-resource');
insert into Practica1 (nombre, palabraSecreta) values ('Maxine Giannassi', 'tertiary');
insert into Practica1 (nombre, palabraSecreta) values ('Prince Leggan', 'asymmetric');
insert into Practica1 (nombre, palabraSecreta) values ('Lida Tomek', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Timothee Dani', 'high-level');
insert into Practica1 (nombre, palabraSecreta) values ('Petronille Clack', 'Advanced');
insert into Practica1 (nombre, palabraSecreta) values ('Guilbert Eseler', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Row Weathers', 'Multi-channelled');
insert into Practica1 (nombre, palabraSecreta) values ('Vilhelmina Tosdevin', 'flexibility');
insert into Practica1 (nombre, palabraSecreta) values ('Rowan Albrook', 'incremental');
insert into Practica1 (nombre, palabraSecreta) values ('Jeannie Yushachkov', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Corrie Darke', 'flexibility');
insert into Practica1 (nombre, palabraSecreta) values ('Corrina Realy', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Valma Fulstow', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Valli Hampton', 'Programmable');
insert into Practica1 (nombre, palabraSecreta) values ('Rafaello Simonetti', 'maximized');
insert into Practica1 (nombre, palabraSecreta) values ('Patten Robak', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Marrissa Bottle', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Matthus Prozillo', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Minnie Creaney', 'budgetary management');
insert into Practica1 (nombre, palabraSecreta) values ('Jordon Brownsall', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Rodge Duggan', 'Seamless');
insert into Practica1 (nombre, palabraSecreta) values ('Hector Gellier', 'Ergonomic');
insert into Practica1 (nombre, palabraSecreta) values ('Milzie Woollacott', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Franciskus Spenclay', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Joaquin Cosser', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Diandra Haxby', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Mikol Karpushkin', 'mission-critical');
insert into Practica1 (nombre, palabraSecreta) values ('Paige Chidzoy', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Hamid Enderle', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Shaylyn Radnedge', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Karolina Dignum', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Tedi Waadenburg', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Angele Vallintine', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Elke Stockbridge', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Abel Fibbens', 'structure');
insert into Practica1 (nombre, palabraSecreta) values ('Chickie Enns', '4th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Lil Fasler', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Cord Scotland', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Tonia Hambly', 'methodology');
insert into Practica1 (nombre, palabraSecreta) values ('Gaby Shead', '3rd generation');
insert into Practica1 (nombre, palabraSecreta) values ('Gina Sudddard', 'Programmable');
insert into Practica1 (nombre, palabraSecreta) values ('Lindy Lefort', 'Organic');
insert into Practica1 (nombre, palabraSecreta) values ('Roselia Mycroft', 'Devolved');
insert into Practica1 (nombre, palabraSecreta) values ('Emlen Blindermann', 'budgetary management');
insert into Practica1 (nombre, palabraSecreta) values ('Florie Rees', 'transitional');
insert into Practica1 (nombre, palabraSecreta) values ('Fey Boothe', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Mala Forte', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Tann Tagg', 'standardization');
insert into Practica1 (nombre, palabraSecreta) values ('Gar Coveney', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Zita Warkup', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Arel Kilshaw', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Corie Ferrie', 'Object-based');
insert into Practica1 (nombre, palabraSecreta) values ('Jacquenetta Bedrosian', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Tresa Dressel', 'Function-based');
insert into Practica1 (nombre, palabraSecreta) values ('Nathan Axby', 'function');
insert into Practica1 (nombre, palabraSecreta) values ('Lindy Turtle', 'multi-tasking');
insert into Practica1 (nombre, palabraSecreta) values ('Colman Corsan', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Andros Bebbington', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Adair Radcliffe', 'tertiary');
insert into Practica1 (nombre, palabraSecreta) values ('Madelina McInerney', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Tomaso Phillott', 'directional');
insert into Practica1 (nombre, palabraSecreta) values ('Erasmus Ledbury', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Paquito Perigeaux', 'mission-critical');
insert into Practica1 (nombre, palabraSecreta) values ('Walton MacArthur', 'Front-line');
insert into Practica1 (nombre, palabraSecreta) values ('Eliot Woosnam', 'object-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Violante Llorens', 'dynamic');
insert into Practica1 (nombre, palabraSecreta) values ('Fredericka Assard', 'Focused');
insert into Practica1 (nombre, palabraSecreta) values ('Tiffany Fairweather', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Michale Essam', 'Multi-channelled');
insert into Practica1 (nombre, palabraSecreta) values ('Benoit Fitzharris', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Tiffy Yanin', 'User-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Naoma Dillimore', 'superstructure');
insert into Practica1 (nombre, palabraSecreta) values ('Marga Scrancher', 'groupware');
insert into Practica1 (nombre, palabraSecreta) values ('Nobie Gleadhell', 'grid-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Kalle Denington', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Aldus Hatry', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Myrlene Comley', 'real-time');
insert into Practica1 (nombre, palabraSecreta) values ('Anitra Ayerst', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Vance Zanelli', 'architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Marcy Deeprose', 'transitional');
insert into Practica1 (nombre, palabraSecreta) values ('Arabel Greenin', 'Profound');
insert into Practica1 (nombre, palabraSecreta) values ('Nicky Rockingham', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Zuzana Bodker', 'functionalities');
insert into Practica1 (nombre, palabraSecreta) values ('Lora Minett', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Umeko Napoli', 'full-range');
insert into Practica1 (nombre, palabraSecreta) values ('Alane Yurevich', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Tani Sebrook', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Calla Blenkensop', 'mobile');
insert into Practica1 (nombre, palabraSecreta) values ('Goldi Roderighi', 'Synergistic');
insert into Practica1 (nombre, palabraSecreta) values ('Codie Vlach', 'optimal');
insert into Practica1 (nombre, palabraSecreta) values ('Marysa Allsopp', 'knowledge user');
insert into Practica1 (nombre, palabraSecreta) values ('Bethina Pinkett', 'focus group');
insert into Practica1 (nombre, palabraSecreta) values ('Gardener Simonyi', 'next generation');
insert into Practica1 (nombre, palabraSecreta) values ('Rosabel Sterzaker', 'optimal');
insert into Practica1 (nombre, palabraSecreta) values ('Eberto Schreiner', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Gran Ovens', 'artificial intelligence');
insert into Practica1 (nombre, palabraSecreta) values ('Bartolemo Temblett', 'full-range');
insert into Practica1 (nombre, palabraSecreta) values ('Jillana Roglieri', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Henri Larret', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Kordula Jaram', 'knowledge base');
insert into Practica1 (nombre, palabraSecreta) values ('Karyn McEnhill', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Ivor Guiot', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Anthia Guard', 'workforce');
insert into Practica1 (nombre, palabraSecreta) values ('Alameda Demangeot', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Nicholle Frith', 'Compatible');
insert into Practica1 (nombre, palabraSecreta) values ('Tori Glossup', 'intranet');
insert into Practica1 (nombre, palabraSecreta) values ('Teodora Bonifazio', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Kathrine Coale', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Celestine Rapson', 'Horizontal');
insert into Practica1 (nombre, palabraSecreta) values ('Erny Plumstead', 'Profit-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Jenni Oneile', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Erinn Mattingson', 'Intuitive');
insert into Practica1 (nombre, palabraSecreta) values ('Janos Iacoviello', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Joana Stoodale', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Birch Buckam', 'instruction set');
insert into Practica1 (nombre, palabraSecreta) values ('Roseanne McCreery', 'systematic');
insert into Practica1 (nombre, palabraSecreta) values ('Parrnell Pischof', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Bryna Crumpe', 'actuating');
insert into Practica1 (nombre, palabraSecreta) values ('Hebert Dale', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Francene Meriet', 'local');
insert into Practica1 (nombre, palabraSecreta) values ('Margarette Pieroni', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Frank Pedden', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Camel Drohane', 'Advanced');
insert into Practica1 (nombre, palabraSecreta) values ('Tiertza Dilon', '3rd generation');
insert into Practica1 (nombre, palabraSecreta) values ('Loise Olivey', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Morey Lyall', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Corrie McGilleghole', 'Implemented');
insert into Practica1 (nombre, palabraSecreta) values ('Rois De Freitas', '4th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Holly-anne Stife', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Kirsten Yvens', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Margaret MacGillacolm', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Dulcia Mercer', 'Self-enabling');
insert into Practica1 (nombre, palabraSecreta) values ('Charleen Folkes', 'real-time');
insert into Practica1 (nombre, palabraSecreta) values ('Raphael Decaze', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Poul Carrington', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Bronson Verlinden', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Mickie O''Carrol', 'Horizontal');
insert into Practica1 (nombre, palabraSecreta) values ('Cecile Lewnden', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Jasper Raysdale', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Rivy McClune', 'multi-tasking');
insert into Practica1 (nombre, palabraSecreta) values ('Stevana Igo', 'User-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Becka Rosenberger', 'composite');
insert into Practica1 (nombre, palabraSecreta) values ('Paddie Niland', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Pietrek McVie', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Vernor Mutter', 'protocol');
insert into Practica1 (nombre, palabraSecreta) values ('Edyth Pardue', 'Cross-group');
insert into Practica1 (nombre, palabraSecreta) values ('Dawn Du Plantier', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Aggy McGinley', 'disintermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Haleigh Woodroofe', 'incremental');
insert into Practica1 (nombre, palabraSecreta) values ('Ross Brew', 'neutral');
insert into Practica1 (nombre, palabraSecreta) values ('Mahmoud Craggs', 'Pre-emptive');
insert into Practica1 (nombre, palabraSecreta) values ('Coralyn Hutchin', 'Reverse-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Austine Brambill', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Arliene Kemmis', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Archibold Slocket', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Frasquito Cordet', 'responsive');
insert into Practica1 (nombre, palabraSecreta) values ('Taylor Mortlock', 'Expanded');
insert into Practica1 (nombre, palabraSecreta) values ('Lu Pietsma', 'asynchronous');
insert into Practica1 (nombre, palabraSecreta) values ('Clywd Trussman', 'synergy');
insert into Practica1 (nombre, palabraSecreta) values ('Valeria Janota', 'extranet');
insert into Practica1 (nombre, palabraSecreta) values ('Care Rummer', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Arri Brugh', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Fielding Wasiela', 'upward-trending');
insert into Practica1 (nombre, palabraSecreta) values ('Red Tompsett', 'Ameliorated');
insert into Practica1 (nombre, palabraSecreta) values ('Berenice Leuty', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Wylma Harlin', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Lorri Pyson', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Ives Oluwatoyin', 'asynchronous');
insert into Practica1 (nombre, palabraSecreta) values ('Bobby Tavinor', 'stable');
insert into Practica1 (nombre, palabraSecreta) values ('Anastasie Phipps', 'encryption');
insert into Practica1 (nombre, palabraSecreta) values ('Willamina Goffe', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Junina Wash', 'heuristic');
insert into Practica1 (nombre, palabraSecreta) values ('Arvin Poff', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Estelle Merrin', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Vinson Clemmett', 'circuit');
insert into Practica1 (nombre, palabraSecreta) values ('Bogey Blissitt', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Igor Tremonte', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Tarah Petras', 'full-range');
insert into Practica1 (nombre, palabraSecreta) values ('Amber Exton', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Roslyn Simeoli', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Garnet Stapele', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Moselle Castellaccio', 'Networked');
insert into Practica1 (nombre, palabraSecreta) values ('Xavier Casari', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Tiff Laurenson', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Bordie Seakin', 'monitoring');
insert into Practica1 (nombre, palabraSecreta) values ('Virgie Danovich', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Francesco Flescher', 'human-resource');
insert into Practica1 (nombre, palabraSecreta) values ('Beulah Rouzet', 'Up-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Gilly MacSkeaghan', 'transitional');
insert into Practica1 (nombre, palabraSecreta) values ('Carney MacPadene', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Vivyan Schlagh', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Glory Trimby', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Caroline Golder', 'Public-key');
insert into Practica1 (nombre, palabraSecreta) values ('Johny Jowers', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Leandra Wenger', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Durante Grigorescu', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Tucker Abramow', 'hub');
insert into Practica1 (nombre, palabraSecreta) values ('Perren Wilbor', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Yuri De Vere', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Michell Shepheard', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Lanae Beaze', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Mil Gilluley', 'Distributed');
insert into Practica1 (nombre, palabraSecreta) values ('Welsh Daout', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Aldwin Guynemer', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Cristian Sackey', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Jamison Flott', 'explicit');
insert into Practica1 (nombre, palabraSecreta) values ('Stephana Mayhew', 'Reverse-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Alwin Tyas', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Kienan Nunnery', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Janaye Provest', 'moderator');
insert into Practica1 (nombre, palabraSecreta) values ('Eldin Barke', 'Configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Ferdie McGuinley', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Virgina Hylton', 'help-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Casar Armin', 'software');
insert into Practica1 (nombre, palabraSecreta) values ('Mersey Vaughten', 'product');
insert into Practica1 (nombre, palabraSecreta) values ('Rafferty Cummins', 'Business-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Sunshine Bourgeois', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Delly Grandison', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Carolin Heims', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Winni Gramer', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Sheff Loving', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Ede Ethelston', 'uniform');
insert into Practica1 (nombre, palabraSecreta) values ('Terza Bakeup', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Jarred Buxy', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Rosemonde Crippin', 'Monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Dyna Tromans', 'customer loyalty');
insert into Practica1 (nombre, palabraSecreta) values ('Rickey Cotilard', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Kylynn Speddin', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Arny Pickthorne', 'Synergistic');
insert into Practica1 (nombre, palabraSecreta) values ('Kaila Philippeaux', 'synergy');
insert into Practica1 (nombre, palabraSecreta) values ('Herc Deshon', 'asymmetric');
insert into Practica1 (nombre, palabraSecreta) values ('Vally Danby', 'Organized');
insert into Practica1 (nombre, palabraSecreta) values ('Yorgos Valintine', 'solution');
insert into Practica1 (nombre, palabraSecreta) values ('Cornelius Buttrum', 'reciprocal');
insert into Practica1 (nombre, palabraSecreta) values ('Georgeta Melloi', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Melly Fehner', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Anissa Allanson', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Mariellen Hackleton', 'hierarchy');
insert into Practica1 (nombre, palabraSecreta) values ('Cyb Stoyell', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Janna Campion', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Barde Moughtin', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Weylin Ivantyev', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Kory Capeling', 'Focused');
insert into Practica1 (nombre, palabraSecreta) values ('Hephzibah Newbigging', 'Innovative');
insert into Practica1 (nombre, palabraSecreta) values ('Uri Schuh', 'bandwidth-monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Saraann Skittle', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Swen McKyrrelly', 'throughput');
insert into Practica1 (nombre, palabraSecreta) values ('Brigham Gagg', 'stable');
insert into Practica1 (nombre, palabraSecreta) values ('Shermie Milesap', 'attitude-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Max Wallbanks', 'empowering');
insert into Practica1 (nombre, palabraSecreta) values ('Coop Heam', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Adolpho Fearnley', 'paradigm');
insert into Practica1 (nombre, palabraSecreta) values ('Karoly Shuard', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Mitch Beves', 'eco-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Larry Doche', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Rycca Snoxill', 'mission-critical');
insert into Practica1 (nombre, palabraSecreta) values ('Ardella Strevens', 'Reactive');
insert into Practica1 (nombre, palabraSecreta) values ('Laurie Whetnell', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Rhys Dubbin', 'attitude');
insert into Practica1 (nombre, palabraSecreta) values ('Rozella Clemo', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Larry Cleare', 'Face to face');
insert into Practica1 (nombre, palabraSecreta) values ('Benedetta Uebel', 'Horizontal');
insert into Practica1 (nombre, palabraSecreta) values ('Othello Goldstein', 'Team-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Alisun Pavie', 'Vision-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Joli Arboin', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Hannah Romushkin', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Orton Stroder', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Adena MacGaffey', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Des McArley', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Chryste Bosket', 'product');
insert into Practica1 (nombre, palabraSecreta) values ('Teirtza Tredget', 'Organic');
insert into Practica1 (nombre, palabraSecreta) values ('Sheppard Mustoe', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Jillane Gietz', 'Integrated');
insert into Practica1 (nombre, palabraSecreta) values ('Myrtle Moakes', 'Automated');
insert into Practica1 (nombre, palabraSecreta) values ('Hattie Figurski', 'Exclusive');
insert into Practica1 (nombre, palabraSecreta) values ('Minny Liverseege', 'Configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Grannie Spehr', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Bruis Coppin', 'Switchable');
insert into Practica1 (nombre, palabraSecreta) values ('Mary Taks', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Gerti Fitzroy', 'high-level');
insert into Practica1 (nombre, palabraSecreta) values ('Bree Baroch', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Friederike Slatten', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Ruttger Royste', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Portia MacGowan', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Genia Goalby', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Armstrong Oseman', 'Right-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Earvin Wintle', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Dre Steptowe', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Meredith Kowalik', 'Compatible');
insert into Practica1 (nombre, palabraSecreta) values ('Mellisa Beentjes', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Torry Mc Trusty', 'definition');
insert into Practica1 (nombre, palabraSecreta) values ('Corrinne O''Lyhane', 'intermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Piggy Gristwood', 'encryption');
insert into Practica1 (nombre, palabraSecreta) values ('Juli Jarlmann', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Brody MacPaden', 'adapter');
