insert into Practica1 (nombre, palabraSecreta) values ('Gabie Sibborn', 'systematic');
insert into Practica1 (nombre, palabraSecreta) values ('Cass Glenfield', 'Up-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Jo ann Bruckent', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Heather Nalder', 'disintermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Findley Masserel', 'well-modulated');
insert into Practica1 (nombre, palabraSecreta) values ('Flori Croyser', 'function');
insert into Practica1 (nombre, palabraSecreta) values ('Derk Gange', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Reese Paute', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Nicol Bagge', 'knowledge base');
insert into Practica1 (nombre, palabraSecreta) values ('Mallory Gorce', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Hildagarde Cabel', 'Graphic Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Ally Selwyne', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Tess Redihough', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Sabine Beaford', 'user-facing');
insert into Practica1 (nombre, palabraSecreta) values ('Nydia Nettles', 'Right-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Hyacinth Allwood', 'intranet');
insert into Practica1 (nombre, palabraSecreta) values ('Katy Bartunek', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Huntington Woodyatt', 'systematic');
insert into Practica1 (nombre, palabraSecreta) values ('Teressa Tutt', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Clyde Ledbetter', 'Networked');
insert into Practica1 (nombre, palabraSecreta) values ('Trixy Meagher', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Dwain Treher', 'Virtual');
insert into Practica1 (nombre, palabraSecreta) values ('Bette-ann Dodle', 'workforce');
insert into Practica1 (nombre, palabraSecreta) values ('Bert Sworder', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Ashil Merrell', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Merv Sawle', 'Synchronised');
insert into Practica1 (nombre, palabraSecreta) values ('Stephie Snodin', 'Business-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Sven Lideard', 'multimedia');
insert into Practica1 (nombre, palabraSecreta) values ('Mill Gumme', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Izak Onraet', 'upward-trending');
insert into Practica1 (nombre, palabraSecreta) values ('L;urette Guerrieri', 'demand-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Ginny Breward', 'Diverse');
insert into Practica1 (nombre, palabraSecreta) values ('Kerk Clipson', 'conglomeration');
insert into Practica1 (nombre, palabraSecreta) values ('Nolly Everest', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Laverne Edinburgh', 'grid-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Judie Fozzard', 'dedicated');
insert into Practica1 (nombre, palabraSecreta) values ('Rutger Houten', 'even-keeled');
insert into Practica1 (nombre, palabraSecreta) values ('Roderich Gissing', 'flexibility');
insert into Practica1 (nombre, palabraSecreta) values ('Dulcine Olner', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Bethanne Girardoni', 'zero defect');
insert into Practica1 (nombre, palabraSecreta) values ('Meredeth Almon', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Nikki Stembridge', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Chad Rowston', 'Distributed');
insert into Practica1 (nombre, palabraSecreta) values ('Pryce Tilly', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Nevil Swaffield', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Nealy Sangra', 'human-resource');
insert into Practica1 (nombre, palabraSecreta) values ('Ileane Scorey', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Way Bold', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Vicki Camoletto', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Ted Preston', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Dynah Toft', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Kirby Kryszkiecicz', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Marcille Worral', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Emmerich Sothcott', 'Sharable');
insert into Practica1 (nombre, palabraSecreta) values ('Faunie Chawkley', 'heuristic');
insert into Practica1 (nombre, palabraSecreta) values ('Rosy Newcome', 'Front-line');
insert into Practica1 (nombre, palabraSecreta) values ('Libby Vaar', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Melodee Swinford', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Pepita Antoniou', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Ann-marie Pimmocke', 'utilisation');
insert into Practica1 (nombre, palabraSecreta) values ('Dallon Traves', 'open architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Loise Clitherow', 'open system');
insert into Practica1 (nombre, palabraSecreta) values ('Denver Heberden', 'Distributed');
insert into Practica1 (nombre, palabraSecreta) values ('Gardie Woolerton', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Mandel McReath', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Shanda Colaton', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Nil Humpage', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Justus Hartgill', 'Monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Fiona Budnk', 'product');
insert into Practica1 (nombre, palabraSecreta) values ('Orville Keyzman', 'encoding');
insert into Practica1 (nombre, palabraSecreta) values ('Nicholas Thurston', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Lynnea Boyton', 'human-resource');
insert into Practica1 (nombre, palabraSecreta) values ('Mandi Dewsbury', 'Right-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Jacquelynn Nare', 'stable');
insert into Practica1 (nombre, palabraSecreta) values ('Tawsha Boulding', 'User-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Jami Crommett', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Winny Kuschke', 'Reverse-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Friederike Dybell', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Humphrey Mancer', 'workforce');
insert into Practica1 (nombre, palabraSecreta) values ('Nealson Penhale', 'dedicated');
insert into Practica1 (nombre, palabraSecreta) values ('Rudyard Corryer', 'systemic');
insert into Practica1 (nombre, palabraSecreta) values ('Ulrike Gorman', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Emalee Vittori', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Charlena Sturgeon', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Karee Petrasso', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Lewie Bullingham', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Nikolos Bonome', 'database');
insert into Practica1 (nombre, palabraSecreta) values ('Reuven Lenoir', 'Secured');
insert into Practica1 (nombre, palabraSecreta) values ('Vitia Elies', 'neutral');
insert into Practica1 (nombre, palabraSecreta) values ('Meaghan Barnewelle', 'Team-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Nalani Persitt', 'knowledge base');
insert into Practica1 (nombre, palabraSecreta) values ('Selestina McNiff', 'Upgradable');
insert into Practica1 (nombre, palabraSecreta) values ('Alexandros Leisman', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Deonne Cristofolini', 'User-friendly');
insert into Practica1 (nombre, palabraSecreta) values ('Krisha Stanaway', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Clarette Rillatt', 'Profit-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Grayce Hoggins', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Bert Corwood', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Tito Summerfield', 'well-modulated');
insert into Practica1 (nombre, palabraSecreta) values ('Paulina Francke', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Bernard Peel', 'local');
insert into Practica1 (nombre, palabraSecreta) values ('Bing Carding', 'forecast');
insert into Practica1 (nombre, palabraSecreta) values ('Odele Pedrozzi', 'Mandatory');
insert into Practica1 (nombre, palabraSecreta) values ('Judye Lorenzini', 'De-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Gualterio Flori', 'protocol');
insert into Practica1 (nombre, palabraSecreta) values ('Inger Adamsen', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Letta Dyster', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Jenni Belliveau', '5th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Belva Byard', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Estella Manifield', 'moderator');
insert into Practica1 (nombre, palabraSecreta) values ('Netti Carlon', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Isidoro Laxton', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Rikki MacGlory', 'attitude');
insert into Practica1 (nombre, palabraSecreta) values ('Cesar Eisikowitch', 'Public-key');
insert into Practica1 (nombre, palabraSecreta) values ('Barbra Scrivin', 'national');
insert into Practica1 (nombre, palabraSecreta) values ('Calley Doree', 'Automated');
insert into Practica1 (nombre, palabraSecreta) values ('Pablo Menendes', 'grid-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Ricardo Cuerdale', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Charisse Fishby', 'zero defect');
insert into Practica1 (nombre, palabraSecreta) values ('Roanna Summons', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Kin Baalham', 'Function-based');
insert into Practica1 (nombre, palabraSecreta) values ('Care Duggan', 'Distributed');
insert into Practica1 (nombre, palabraSecreta) values ('Patti Etuck', 'Compatible');
insert into Practica1 (nombre, palabraSecreta) values ('Rickard Ruppert', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Elinor Rawsen', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Guenna Grenshiels', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Dode Ionesco', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Marilin Kalvin', 'Monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Arleen Scotchmor', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Crystal Ollivierre', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Herc Loude', 'Virtual');
insert into Practica1 (nombre, palabraSecreta) values ('Paddy Dooland', 'national');
insert into Practica1 (nombre, palabraSecreta) values ('Denver Stonestreet', 'national');
insert into Practica1 (nombre, palabraSecreta) values ('Claudianus Nutbeam', 'hierarchy');
insert into Practica1 (nombre, palabraSecreta) values ('Nessy Patridge', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Arnie Walcot', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Gayler Muncer', 'heuristic');
insert into Practica1 (nombre, palabraSecreta) values ('Shepherd Garrud', 'Triple-buffered');
insert into Practica1 (nombre, palabraSecreta) values ('Ikey Rettie', 'core');
insert into Practica1 (nombre, palabraSecreta) values ('Gilligan Wyndham', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Rogers Lorryman', 'software');
insert into Practica1 (nombre, palabraSecreta) values ('Corly Mendes', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Madalyn McQuillin', 'definition');
insert into Practica1 (nombre, palabraSecreta) values ('Skipton Piotrkowski', 'budgetary management');
insert into Practica1 (nombre, palabraSecreta) values ('Burlie Burrett', 'reciprocal');
insert into Practica1 (nombre, palabraSecreta) values ('Brinna Erricker', 'intermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Matty De Gowe', 'Grass-roots');
insert into Practica1 (nombre, palabraSecreta) values ('Claire Habgood', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Perren Domenicone', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Tyrone McDonough', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Addia Akett', 'full-range');
insert into Practica1 (nombre, palabraSecreta) values ('Ardys Collyer', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Horatius Howel', 'matrices');
insert into Practica1 (nombre, palabraSecreta) values ('Harriot Staines', 'core');
insert into Practica1 (nombre, palabraSecreta) values ('Myra Lohrensen', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Otha Eagleton', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Findlay Kewzick', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Sonny Cordel', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Daron O''Currane', 'Switchable');
insert into Practica1 (nombre, palabraSecreta) values ('Brandea Woodbridge', 'executive');
insert into Practica1 (nombre, palabraSecreta) values ('Suzy Fortye', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Jo Roney', 'disintermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Ferris Bemand', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Tabby Braunston', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Gabriele Gentile', 'installation');
insert into Practica1 (nombre, palabraSecreta) values ('Bessy Tatham', 'open architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Letitia Coomer', 'bandwidth-monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Rog Donaho', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Zora Thorndycraft', 'moratorium');
insert into Practica1 (nombre, palabraSecreta) values ('Nedda Bris', 'solution');
insert into Practica1 (nombre, palabraSecreta) values ('Florentia Walework', 'Focused');
insert into Practica1 (nombre, palabraSecreta) values ('Nedi Walster', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Dal Poag', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Larisa Devenport', 'Secured');
insert into Practica1 (nombre, palabraSecreta) values ('Annamaria Muckley', 'Integrated');
insert into Practica1 (nombre, palabraSecreta) values ('Raynell Davidow', 'Right-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Walliw McPhilip', 'workforce');
insert into Practica1 (nombre, palabraSecreta) values ('Greggory Hulburd', 'upward-trending');
insert into Practica1 (nombre, palabraSecreta) values ('Liv Eggers', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Simmonds Halwell', 'Diverse');
insert into Practica1 (nombre, palabraSecreta) values ('Theo Pigne', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Zea Binny', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Konstantin Skelcher', 'Ameliorated');
insert into Practica1 (nombre, palabraSecreta) values ('Marguerite Sworn', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Athena Wilmington', 'maximized');
insert into Practica1 (nombre, palabraSecreta) values ('Rana Probyn', 'Mandatory');
insert into Practica1 (nombre, palabraSecreta) values ('Hodge Munnis', 'Enhanced');
insert into Practica1 (nombre, palabraSecreta) values ('Jobye Farebrother', 'hierarchy');
insert into Practica1 (nombre, palabraSecreta) values ('Coleen Snoxill', 'context-sensitive');
insert into Practica1 (nombre, palabraSecreta) values ('Clement Maypother', 'synergy');
insert into Practica1 (nombre, palabraSecreta) values ('Lane Walesby', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Teador Sissons', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Rennie Van Waadenburg', 'tertiary');
insert into Practica1 (nombre, palabraSecreta) values ('Jaquenette Mirrlees', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Kirstin Linham', 'Seamless');
insert into Practica1 (nombre, palabraSecreta) values ('Simonette Clough', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Jazmin Lyston', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Johannah Lowdyane', 'dedicated');
insert into Practica1 (nombre, palabraSecreta) values ('Nessy Drewett', 'Innovative');
insert into Practica1 (nombre, palabraSecreta) values ('Barbabas Champ', 'Up-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Zorina Woof', 'bandwidth-monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Ronalda Tuckie', 'throughput');
insert into Practica1 (nombre, palabraSecreta) values ('Roby Phuprate', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Rahel Briggdale', 'focus group');
insert into Practica1 (nombre, palabraSecreta) values ('Olia Rainer', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Jamil Goudge', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Kipp Sallis', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Fee Whenman', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Paten Websdale', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Grantham Chalcot', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Anderea Tiffin', 'groupware');
insert into Practica1 (nombre, palabraSecreta) values ('Andres Loveitt', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Faye Powys', 'global');
insert into Practica1 (nombre, palabraSecreta) values ('Paulie Dole', 'Digitized');
insert into Practica1 (nombre, palabraSecreta) values ('Elijah Pinnion', 'solution-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Joane Farnan', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Angel Sinnie', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Terry Beavan', 'Profound');
insert into Practica1 (nombre, palabraSecreta) values ('Vanna Cordero', 'concept');
insert into Practica1 (nombre, palabraSecreta) values ('Raul Bouttell', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Valma Asee', 'monitoring');
insert into Practica1 (nombre, palabraSecreta) values ('Fabio Duke', 'Reverse-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Ronni Coatham', 'definition');
insert into Practica1 (nombre, palabraSecreta) values ('Ferguson Elcy', 'bandwidth-monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Willey Voice', 'moratorium');
insert into Practica1 (nombre, palabraSecreta) values ('Pearle Degli Abbati', 'synergy');
insert into Practica1 (nombre, palabraSecreta) values ('Graig Hurley', 'Assimilated');
insert into Practica1 (nombre, palabraSecreta) values ('Bealle Skey', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Nerty Coaster', 'mobile');
insert into Practica1 (nombre, palabraSecreta) values ('Farris Keri', 'conglomeration');
insert into Practica1 (nombre, palabraSecreta) values ('Cooper Schroeder', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Gardner Spinello', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Haskell Meeson', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Bobbie Arblaster', 'context-sensitive');
insert into Practica1 (nombre, palabraSecreta) values ('Grace Helliwell', 'Advanced');
insert into Practica1 (nombre, palabraSecreta) values ('Dorrie Lafont', 'Profit-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Issiah McIntee', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Ibbie Duffill', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Willard Caselick', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Hamil Bedrosian', 'Public-key');
insert into Practica1 (nombre, palabraSecreta) values ('Ronny Wagge', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Marlene Spaducci', 'national');
insert into Practica1 (nombre, palabraSecreta) values ('Ricki Quantrill', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Leigha Lune', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Tobiah Seiter', 'User-friendly');
insert into Practica1 (nombre, palabraSecreta) values ('Iago Schurcke', '24/7');
insert into Practica1 (nombre, palabraSecreta) values ('Lucky Smidmoor', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Cal Ludron', 'attitude-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Gustavus Huniwall', 'Exclusive');
insert into Practica1 (nombre, palabraSecreta) values ('Lurline Djakovic', 'optimal');
insert into Practica1 (nombre, palabraSecreta) values ('Alyse Togwell', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Hunter Bridgnell', 'synergy');
insert into Practica1 (nombre, palabraSecreta) values ('Anny Pow', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Chance Fidoe', 'bandwidth-monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Justino Pellant', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Hagen Antonoyev', 'User-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Ertha Pitman', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Jody Helliar', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Ilario Markl', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Petronilla Gilchrest', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Jacquetta Circuit', 'bandwidth-monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Fredia Flood', 'next generation');
insert into Practica1 (nombre, palabraSecreta) values ('Farand Pawlicki', 'impactful');
insert into Practica1 (nombre, palabraSecreta) values ('Talbert Rigney', 'asynchronous');
insert into Practica1 (nombre, palabraSecreta) values ('Tedd Waterdrinker', 'Advanced');
insert into Practica1 (nombre, palabraSecreta) values ('Harri Kirkland', 'budgetary management');
insert into Practica1 (nombre, palabraSecreta) values ('Alistair Barajaz', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Kingston Laffan', 'Ergonomic');
insert into Practica1 (nombre, palabraSecreta) values ('Ruthie Salerno', 'workforce');
insert into Practica1 (nombre, palabraSecreta) values ('Den Ivanenko', 'Graphic Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Bellina Raeburn', 'upward-trending');
insert into Practica1 (nombre, palabraSecreta) values ('Idalia Avrashin', 'methodology');
insert into Practica1 (nombre, palabraSecreta) values ('Gorden MacAlroy', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Morgen Asbury', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Wolfy O''Dyvoie', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Vail Welband', 'success');
insert into Practica1 (nombre, palabraSecreta) values ('Collen Eldred', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Steffen Rapley', 'system engine');
insert into Practica1 (nombre, palabraSecreta) values ('Hodge Sandcraft', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Banky Priestland', 'systemic');
insert into Practica1 (nombre, palabraSecreta) values ('Tabbie Rowsel', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Theodor Garstang', 'adapter');
insert into Practica1 (nombre, palabraSecreta) values ('Morey Reade', 'Right-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Emyle Bussetti', 'Networked');
insert into Practica1 (nombre, palabraSecreta) values ('Meghann Philipot', 'support');
insert into Practica1 (nombre, palabraSecreta) values ('Cobb Nancekivell', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Kelsy Valerius', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Ivan Jugging', 'throughput');
insert into Practica1 (nombre, palabraSecreta) values ('Greta Niemetz', 'Sharable');
insert into Practica1 (nombre, palabraSecreta) values ('Gabrielle Bleesing', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Dalia Westlake', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Henrietta Trank', 'De-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Benjy Climar', 'policy');
insert into Practica1 (nombre, palabraSecreta) values ('Bonny Ren', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Casandra Burnall', 'architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Della Amps', 'Organized');
insert into Practica1 (nombre, palabraSecreta) values ('Catriona Beauly', 'bandwidth-monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Tobie Greenset', 'Cloned');
insert into Practica1 (nombre, palabraSecreta) values ('Karrah Cool', 'Virtual');
insert into Practica1 (nombre, palabraSecreta) values ('Maurita Vanns', 'focus group');
insert into Practica1 (nombre, palabraSecreta) values ('Iosep Dewsnap', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Ginger Killwick', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Courtnay Kinworthy', 'throughput');
insert into Practica1 (nombre, palabraSecreta) values ('Edwina Matveiko', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Ambur Morforth', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Mario Iacomini', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Moss Gisburn', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Janis Bampkin', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Melessa Bayfield', 'asynchronous');
insert into Practica1 (nombre, palabraSecreta) values ('Andria Boichat', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Gareth Featenby', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Cordula Kording', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Rudolfo Hackworthy', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Hedwiga Stollery', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Lilah Frangione', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Maryrose Ganford', 'Fully-configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Vittoria Callister', 'Assimilated');
insert into Practica1 (nombre, palabraSecreta) values ('Leslie Barlthrop', 'uniform');
insert into Practica1 (nombre, palabraSecreta) values ('Tailor Westhead', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Sigismondo Reely', 'Ameliorated');
insert into Practica1 (nombre, palabraSecreta) values ('Roze Gabe', 'explicit');
insert into Practica1 (nombre, palabraSecreta) values ('Ethe Bodley', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Reinaldo Tomley', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Hanan Cribbin', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Hyacinth Neljes', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Rochelle Le Borgne', 'responsive');
insert into Practica1 (nombre, palabraSecreta) values ('Filippa Somerbell', 'Automated');
insert into Practica1 (nombre, palabraSecreta) values ('Josey Toulamain', 'productivity');
insert into Practica1 (nombre, palabraSecreta) values ('Raychel Towle', 'Switchable');
insert into Practica1 (nombre, palabraSecreta) values ('Dana Turfitt', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Tandie Auld', 'portal');
insert into Practica1 (nombre, palabraSecreta) values ('Amalea Chichgar', 'frame');
insert into Practica1 (nombre, palabraSecreta) values ('Lek Husby', 'internet solution');
insert into Practica1 (nombre, palabraSecreta) values ('Marinna Speechly', 'foreground');
insert into Practica1 (nombre, palabraSecreta) values ('Lia Oaten', 'software');
insert into Practica1 (nombre, palabraSecreta) values ('Mariele Sprulls', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Boyce Maginn', 'circuit');
insert into Practica1 (nombre, palabraSecreta) values ('Tracey Ashtonhurst', 'Self-enabling');
insert into Practica1 (nombre, palabraSecreta) values ('Keefer Ellph', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Kora Warburton', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Kaye Delia', 'Enterprise-wide');
insert into Practica1 (nombre, palabraSecreta) values ('Cindee Benoit', 'encryption');
insert into Practica1 (nombre, palabraSecreta) values ('Fayina Tapsell', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Fan Petegree', 'model');
insert into Practica1 (nombre, palabraSecreta) values ('Zabrina Wheeler', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Hildagarde Starrs', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Jarib Toffalo', 'intranet');
insert into Practica1 (nombre, palabraSecreta) values ('Joell Bavidge', 'User-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Joellyn Toppas', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Ferrell Mackie', 'Fully-configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Rustin Keizman', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Larine Lukasen', 'Innovative');
insert into Practica1 (nombre, palabraSecreta) values ('Trude Merrydew', 'internet solution');
insert into Practica1 (nombre, palabraSecreta) values ('Friedrich Soanes', 'Integrated');
insert into Practica1 (nombre, palabraSecreta) values ('Christean Colaco', 'Programmable');
insert into Practica1 (nombre, palabraSecreta) values ('Bowie Coole', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Egbert Czadla', 'application');
insert into Practica1 (nombre, palabraSecreta) values ('Jannel Hawket', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Jerad Esberger', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Kimberlyn Beamiss', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Maxine Espinola', 'database');
insert into Practica1 (nombre, palabraSecreta) values ('Heath Farron', 'background');
insert into Practica1 (nombre, palabraSecreta) values ('Flint Stockhill', 'asynchronous');
insert into Practica1 (nombre, palabraSecreta) values ('Tome Pakes', 'mission-critical');
insert into Practica1 (nombre, palabraSecreta) values ('Myranda Catonnet', 'firmware');
insert into Practica1 (nombre, palabraSecreta) values ('Patsy Lundbech', 'bi-directional');
insert into Practica1 (nombre, palabraSecreta) values ('Emanuele Sinson', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Luigi Faithfull', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Clementina Huleatt', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Grant Rutt', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Harald Kimbrough', 'database');
insert into Practica1 (nombre, palabraSecreta) values ('Conni Steer', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Kacie Storm', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Robinet Josefer', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Kev Collumbell', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Genia Chezelle', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Shoshanna Burges', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Chane Parfitt', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Alexandrina Hawick', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Tybalt Gorwood', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Janka Duly', 'methodology');
insert into Practica1 (nombre, palabraSecreta) values ('Waiter Beadell', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Lionel MacUchadair', 'protocol');
insert into Practica1 (nombre, palabraSecreta) values ('Orsa Puve', 'Intuitive');
insert into Practica1 (nombre, palabraSecreta) values ('Timmie Severwright', 'directional');
insert into Practica1 (nombre, palabraSecreta) values ('Federica Rowatt', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Jecho Howkins', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Merlina Clausson', 'core');
insert into Practica1 (nombre, palabraSecreta) values ('Zara Euesden', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Jess Shanley', 'moratorium');
insert into Practica1 (nombre, palabraSecreta) values ('Karine Dyzart', 'functionalities');
insert into Practica1 (nombre, palabraSecreta) values ('Linea Giurio', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Jorey Loffhead', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Myron Woodland', 'Networked');
insert into Practica1 (nombre, palabraSecreta) values ('Faith Bozward', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Cacilie Twitchett', 'actuating');
insert into Practica1 (nombre, palabraSecreta) values ('Ignaz Cheek', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Tully Caro', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Margaretha Screwton', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Simonne Cairney', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Gallard Hunter', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Merola Bryson', 'application');
insert into Practica1 (nombre, palabraSecreta) values ('Minette Caslett', 'Enterprise-wide');
insert into Practica1 (nombre, palabraSecreta) values ('Carolyne Jagger', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Corabella Paulillo', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Cosette Van der Velde', 'needs-based');
insert into Practica1 (nombre, palabraSecreta) values ('Dorine Custard', 'Automated');
insert into Practica1 (nombre, palabraSecreta) values ('Culver Lawey', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Idalia Jecks', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Kane Steels', 'customer loyalty');
insert into Practica1 (nombre, palabraSecreta) values ('Clement McCosh', '24/7');
insert into Practica1 (nombre, palabraSecreta) values ('Bat Hamblen', 'asynchronous');
insert into Practica1 (nombre, palabraSecreta) values ('Jannel Lytton', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Tedda Esparza', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Meyer Jonsson', 'multimedia');
insert into Practica1 (nombre, palabraSecreta) values ('Isadora Searsby', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Timmi McKillop', 'dynamic');
insert into Practica1 (nombre, palabraSecreta) values ('Archy Fernandez', 'paradigm');
insert into Practica1 (nombre, palabraSecreta) values ('Glynis Boteman', 'Switchable');
insert into Practica1 (nombre, palabraSecreta) values ('Stu Beetles', 'eco-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Raffarty Vanes', 'Inverse');
insert into Practica1 (nombre, palabraSecreta) values ('Aurelia Rubinowicz', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Pedro Stevani', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Josey Maine', 'tertiary');
insert into Practica1 (nombre, palabraSecreta) values ('Deonne Kernley', 'Public-key');
insert into Practica1 (nombre, palabraSecreta) values ('Sharron Blakemore', 'Networked');
insert into Practica1 (nombre, palabraSecreta) values ('Howey Traves', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Mitchael Rickell', 'groupware');
insert into Practica1 (nombre, palabraSecreta) values ('Francoise Caldow', 'background');
insert into Practica1 (nombre, palabraSecreta) values ('Giacobo Jakubiak', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Steward Fettiplace', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Zora Welland', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Gilberto Dan', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Ruggiero Lack', 'Distributed');
insert into Practica1 (nombre, palabraSecreta) values ('Othilie Tejero', 'Synergized');
insert into Practica1 (nombre, palabraSecreta) values ('Tiffani Greenacre', 'Face to face');
insert into Practica1 (nombre, palabraSecreta) values ('Eleni Van Eeden', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Gary Darwin', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Clayborne Gomer', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Darline Blanshard', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Carmella Beaushaw', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Laurent Muff', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Dukie Wurz', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Walliw Bumby', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Constantia D''Onisi', 'Balanced');
insert into Practica1 (nombre, palabraSecreta) values ('Averil Espinha', 'Ameliorated');
insert into Practica1 (nombre, palabraSecreta) values ('Saul Slade', 'adapter');
insert into Practica1 (nombre, palabraSecreta) values ('Gay Colum', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Claudia Gillings', 'encryption');
insert into Practica1 (nombre, palabraSecreta) values ('Courtenay Timothy', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Sephira Chapelhow', 'fault-tolerant');
insert into Practica1 (nombre, palabraSecreta) values ('Artie Matasov', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Juieta Kristoffersson', 'bi-directional');
insert into Practica1 (nombre, palabraSecreta) values ('Carmen Richten', 'Triple-buffered');
insert into Practica1 (nombre, palabraSecreta) values ('Eva MacCallam', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Florrie Crystal', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Abe Amar', 'hierarchy');
insert into Practica1 (nombre, palabraSecreta) values ('Charis Skells', 'directional');
insert into Practica1 (nombre, palabraSecreta) values ('Roxana Isenor', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Magdalene Bucky', 'explicit');
insert into Practica1 (nombre, palabraSecreta) values ('Ludovico McDonagh', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Fern Maggi', 'disintermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Waldo Burrass', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Reider Hussey', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Brent McCloughen', 'executive');
insert into Practica1 (nombre, palabraSecreta) values ('Berthe Schuler', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Ulick Durram', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Ossie Castellino', 'system engine');
insert into Practica1 (nombre, palabraSecreta) values ('Broddie Bonicelli', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Cecilla Champerlen', 'maximized');
insert into Practica1 (nombre, palabraSecreta) values ('Maxie Miguet', 'composite');
insert into Practica1 (nombre, palabraSecreta) values ('Albina Feye', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Lucy Piscot', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Lauraine Norree', '3rd generation');
insert into Practica1 (nombre, palabraSecreta) values ('Oran Dreini', 'application');
insert into Practica1 (nombre, palabraSecreta) values ('Shell Nottingam', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Saidee Ensor', 'Distributed');
insert into Practica1 (nombre, palabraSecreta) values ('Rennie Bigly', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Dulcy Blanning', 'system engine');
insert into Practica1 (nombre, palabraSecreta) values ('Cassius Kestle', 'local');
insert into Practica1 (nombre, palabraSecreta) values ('Francisco Caulwell', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Gwendolin O''Currane', 'Multi-channelled');
insert into Practica1 (nombre, palabraSecreta) values ('Aggi Rojahn', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Adolpho Graeser', 'fault-tolerant');
insert into Practica1 (nombre, palabraSecreta) values ('Merla Gouinlock', 'Horizontal');
insert into Practica1 (nombre, palabraSecreta) values ('Masha Langelay', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Nancy Dinjes', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Marley Waters', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Emery Coom', 'Advanced');
insert into Practica1 (nombre, palabraSecreta) values ('Constance Sheards', 'uniform');
insert into Practica1 (nombre, palabraSecreta) values ('Patricio Mayoh', 'stable');
insert into Practica1 (nombre, palabraSecreta) values ('Urson Lempenny', 'Sharable');
insert into Practica1 (nombre, palabraSecreta) values ('Cazzie MacKniely', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Kinna Casley', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Bee Godfroy', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Cortie Wick', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Lorianne Mayhead', 'user-facing');
insert into Practica1 (nombre, palabraSecreta) values ('Maegan Keward', 'Business-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Hobey Marlowe', 'Exclusive');
insert into Practica1 (nombre, palabraSecreta) values ('Melamie Mathivon', 'bi-directional');
insert into Practica1 (nombre, palabraSecreta) values ('Herve Tompion', 'flexibility');
insert into Practica1 (nombre, palabraSecreta) values ('Kissiah Dale', 'heuristic');
insert into Practica1 (nombre, palabraSecreta) values ('Darcy Biles', 'Implemented');
insert into Practica1 (nombre, palabraSecreta) values ('Orlan Hurdiss', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Liza Alcide', 'Open-architected');
insert into Practica1 (nombre, palabraSecreta) values ('Hillyer Renny', 'system engine');
insert into Practica1 (nombre, palabraSecreta) values ('Michele Idel', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Pauli Jest', 'Ergonomic');
insert into Practica1 (nombre, palabraSecreta) values ('Fraser Maddrah', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Clark Paddison', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Boote Rubenov', 'neutral');
insert into Practica1 (nombre, palabraSecreta) values ('Ignace Huntington', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Niki Goulbourne', 'directional');
insert into Practica1 (nombre, palabraSecreta) values ('Archibaldo Tomanek', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Leonard Fassbindler', 'budgetary management');
insert into Practica1 (nombre, palabraSecreta) values ('Kelcey Dudlestone', 'background');
insert into Practica1 (nombre, palabraSecreta) values ('Lorie Cruickshanks', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Alden Ainscow', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Heidie Roderighi', 'moratorium');
insert into Practica1 (nombre, palabraSecreta) values ('Georas Letch', 'local');
insert into Practica1 (nombre, palabraSecreta) values ('Gusta Stollen', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Jacky Corsar', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Orion Crennell', 'reciprocal');
insert into Practica1 (nombre, palabraSecreta) values ('Huntlee Barbara', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Nathanael Ilyinykh', 'Public-key');
insert into Practica1 (nombre, palabraSecreta) values ('Andra Fitzjohn', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Stephannie Arnald', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Rosabelle Surplice', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Truda Domelaw', 'installation');
insert into Practica1 (nombre, palabraSecreta) values ('Scott Jura', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Bernardina Ramshaw', 'tertiary');
insert into Practica1 (nombre, palabraSecreta) values ('Bobbee Patman', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Demetra Gerholz', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Nanete Whysall', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Jaymee Vinnick', 'local');
insert into Practica1 (nombre, palabraSecreta) values ('Concettina Sinderland', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Sid Crennell', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Heath Shave', 'object-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Robenia Birkmyr', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Annette MacMenemy', 'dedicated');
insert into Practica1 (nombre, palabraSecreta) values ('Lanita Orcott', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Rasia Rapa', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Roslyn Sapson', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Egan Gierhard', 'User-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Lenka Sheringham', 'dynamic');
insert into Practica1 (nombre, palabraSecreta) values ('Ezekiel Brumble', 'real-time');
insert into Practica1 (nombre, palabraSecreta) values ('Nana Hucknall', 'directional');
insert into Practica1 (nombre, palabraSecreta) values ('Priscilla Noon', 'Upgradable');
insert into Practica1 (nombre, palabraSecreta) values ('Sayre Tolley', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Jereme Roskeilly', 'installation');
insert into Practica1 (nombre, palabraSecreta) values ('Thomasine Anning', 'object-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Cristobal Gooderson', 'grid-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Hasty Englefield', 'Intuitive');
insert into Practica1 (nombre, palabraSecreta) values ('Cecily Hexum', 'user-facing');
insert into Practica1 (nombre, palabraSecreta) values ('Elbert Tohill', 'knowledge user');
insert into Practica1 (nombre, palabraSecreta) values ('Ted Kender', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Van Burgin', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Adair Ondrich', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Douglas Hicken', 'user-facing');
insert into Practica1 (nombre, palabraSecreta) values ('Reid Harland', 'methodology');
insert into Practica1 (nombre, palabraSecreta) values ('Conni Waller', 'standardization');
insert into Practica1 (nombre, palabraSecreta) values ('Amii Loade', 'leverage');
insert into Practica1 (nombre, palabraSecreta) values ('Garey Cranmer', 'next generation');
insert into Practica1 (nombre, palabraSecreta) values ('Guillaume Hawtin', 'interface');
insert into Practica1 (nombre, palabraSecreta) values ('Falito Aujean', 'adapter');
insert into Practica1 (nombre, palabraSecreta) values ('Iain Graber', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Hyacinthe Blakeslee', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Jerald Lawes', 'help-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Birgit Wodeland', 'bi-directional');
insert into Practica1 (nombre, palabraSecreta) values ('Torry Peacher', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Morry MacDowall', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Bebe Pethrick', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Boy Kemmet', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Frans Heintsch', 'instruction set');
insert into Practica1 (nombre, palabraSecreta) values ('Raddy Shelton', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Mortie Jzak', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Adriana Such', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Devonna Battman', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Shaw Beagley', 'web-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Tobi Searson', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Hannah Gerant', 'secondary');
insert into Practica1 (nombre, palabraSecreta) values ('Sasha Dungay', 'Enterprise-wide');
insert into Practica1 (nombre, palabraSecreta) values ('Archie Streeten', 'transitional');
insert into Practica1 (nombre, palabraSecreta) values ('Aidan Carmo', '3rd generation');
insert into Practica1 (nombre, palabraSecreta) values ('Elfie Ubsdall', 'budgetary management');
insert into Practica1 (nombre, palabraSecreta) values ('Waylen Steward', 'Self-enabling');
insert into Practica1 (nombre, palabraSecreta) values ('Dyan Ainslee', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Hernando Uppett', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Adlai Snelman', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Christi O''Mohun', 'Graphic Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Rich Vautrey', 'extranet');
insert into Practica1 (nombre, palabraSecreta) values ('Tabitha Geill', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Jocko Byforth', 'real-time');
insert into Practica1 (nombre, palabraSecreta) values ('Anton Mosdell', 'context-sensitive');
insert into Practica1 (nombre, palabraSecreta) values ('Katey Rentz', 'Cross-group');
insert into Practica1 (nombre, palabraSecreta) values ('Cord Limming', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Lynn Preto', 'encoding');
insert into Practica1 (nombre, palabraSecreta) values ('Kristen Priestland', 'maximized');
insert into Practica1 (nombre, palabraSecreta) values ('Adrian Parratt', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Benedetto O''Geaney', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Penrod Lawrenz', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Karylin Yell', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Viki McDonogh', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Matthieu Josifovitz', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Ximenes Ricardot', 'budgetary management');
insert into Practica1 (nombre, palabraSecreta) values ('Ali Osborn', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Shandeigh Maber', 'utilisation');
insert into Practica1 (nombre, palabraSecreta) values ('Terrie Tubritt', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Paulie Penzer', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Patrica Hulkes', 'Reverse-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Abby Blinco', 'Seamless');
insert into Practica1 (nombre, palabraSecreta) values ('Genny Podmore', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Fernanda Matyushenko', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Liesa Charrette', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Melesa Merali', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Talya Dell Casa', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Chrissie Iddy', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Linus Wickey', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Langsdon Cheasman', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Guntar Lorenzini', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Robinet Tranfield', 'even-keeled');
insert into Practica1 (nombre, palabraSecreta) values ('Derick Soan', 'context-sensitive');
insert into Practica1 (nombre, palabraSecreta) values ('Quinlan Grabiec', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Lucien McClory', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Carrie Kolyagin', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Daryl Brimilcome', 'database');
insert into Practica1 (nombre, palabraSecreta) values ('Dee dee Spilling', 'model');
insert into Practica1 (nombre, palabraSecreta) values ('Darlene Bainton', 'Integrated');
insert into Practica1 (nombre, palabraSecreta) values ('Tilda Well', 'model');
insert into Practica1 (nombre, palabraSecreta) values ('Kamila Beckwith', 'multi-tasking');
insert into Practica1 (nombre, palabraSecreta) values ('Stacie Stanyforth', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Willamina Isac', 'Self-enabling');
insert into Practica1 (nombre, palabraSecreta) values ('Max Culham', 'background');
insert into Practica1 (nombre, palabraSecreta) values ('Quincy Woolger', 'knowledge base');
insert into Practica1 (nombre, palabraSecreta) values ('Nickolaus Cottie', 'Digitized');
insert into Practica1 (nombre, palabraSecreta) values ('Ernesta MacFadzan', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Myrvyn Dannel', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Judi Hinge', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Reamonn Fulleylove', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Elmira Odgers', 'Reverse-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Bordy Seviour', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Marillin Barkworth', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Miguel Bukowski', 'hierarchy');
insert into Practica1 (nombre, palabraSecreta) values ('Abagael Eteen', 'multi-tasking');
insert into Practica1 (nombre, palabraSecreta) values ('Alejandrina Booton', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Kain Filov', 'mission-critical');
insert into Practica1 (nombre, palabraSecreta) values ('Gabriella Christescu', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Carolyne Brace', 'Seamless');
insert into Practica1 (nombre, palabraSecreta) values ('Olympia Palk', 'Focused');
insert into Practica1 (nombre, palabraSecreta) values ('Suzette Cornfield', 'protocol');
insert into Practica1 (nombre, palabraSecreta) values ('Margery Skatcher', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Heath Nolin', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Oliver Whisker', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Curry Pohling', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Blinni Bugge', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Colline Tutchings', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Ode Colchett', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Horatia Harrop', 'User-friendly');
insert into Practica1 (nombre, palabraSecreta) values ('Alica Barttrum', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Finn Drillot', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Kippie Kerin', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Billy Manass', 'extranet');
insert into Practica1 (nombre, palabraSecreta) values ('Allissa Greenwell', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Miranda Gulliford', 'empowering');
insert into Practica1 (nombre, palabraSecreta) values ('Benedikt Cathesyed', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Lorant Romney', 'attitude');
insert into Practica1 (nombre, palabraSecreta) values ('Elora Pfertner', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Caryl Pipping', 'open system');
insert into Practica1 (nombre, palabraSecreta) values ('Judon Caldairou', 'Inverse');
insert into Practica1 (nombre, palabraSecreta) values ('Holt Dolby', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Whittaker Suttling', 'forecast');
insert into Practica1 (nombre, palabraSecreta) values ('Olive Sutherland', 'Upgradable');
insert into Practica1 (nombre, palabraSecreta) values ('Flem Ninnoli', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Burl Petrosian', '4th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Annamaria Peile', 'Sharable');
insert into Practica1 (nombre, palabraSecreta) values ('Kimberly Grayham', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Jeana Mico', 'Innovative');
insert into Practica1 (nombre, palabraSecreta) values ('Marianna Snowman', 'instruction set');
insert into Practica1 (nombre, palabraSecreta) values ('Hugo Woollett', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Tilda Kik', 'eco-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Sharon Dagg', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Kyrstin Valens-Smith', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Codie Manoelli', 'empowering');
insert into Practica1 (nombre, palabraSecreta) values ('Hedi Gatlin', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Dario Labb', 'Multi-channelled');
insert into Practica1 (nombre, palabraSecreta) values ('Reuven Nottle', 'Cross-group');
insert into Practica1 (nombre, palabraSecreta) values ('Clerissa Vanini', 'attitude-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Alicea Bilovus', 'protocol');
insert into Practica1 (nombre, palabraSecreta) values ('Margette Matias', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Colas Drews', 'forecast');
insert into Practica1 (nombre, palabraSecreta) values ('Noelle Bointon', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Alia Falcus', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Geoff MacGarrity', 'human-resource');
insert into Practica1 (nombre, palabraSecreta) values ('Ginger Doole', 'knowledge user');
insert into Practica1 (nombre, palabraSecreta) values ('Haze Janjic', 'forecast');
insert into Practica1 (nombre, palabraSecreta) values ('Cristabel Youings', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Alanah Elwel', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Patsy Bywater', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Cornell Paddell', 'software');
insert into Practica1 (nombre, palabraSecreta) values ('Aubert Piddle', 'Team-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Pasquale Askham', 'impactful');
insert into Practica1 (nombre, palabraSecreta) values ('Royal Jeandel', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Evita Furley', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Hanna Elby', '24/7');
insert into Practica1 (nombre, palabraSecreta) values ('Graeme Antoni', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Roth MacCaghan', 'Right-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Ethelind Merigot', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Gael Kennerknecht', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Justino Meadmore', 'core');
insert into Practica1 (nombre, palabraSecreta) values ('Hillyer Junifer', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Tuesday Maffia', 'architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Cherida Driscoll', 'intranet');
insert into Practica1 (nombre, palabraSecreta) values ('Roddy Sate', 'Function-based');
insert into Practica1 (nombre, palabraSecreta) values ('Marika Gutherson', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Ladonna Malinson', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Rosabella Geekin', 'Balanced');
insert into Practica1 (nombre, palabraSecreta) values ('Sheridan McKerrow', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Vivyanne Bleibaum', 'Balanced');
insert into Practica1 (nombre, palabraSecreta) values ('Irv Awty', 'Open-architected');
insert into Practica1 (nombre, palabraSecreta) values ('Eldin Haughan', 'system-worthy');
insert into Practica1 (nombre, palabraSecreta) values ('Tobias Cockney', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Hildy Antonellini', '4th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Xavier Francino', 'heuristic');
insert into Practica1 (nombre, palabraSecreta) values ('Janot Shoemark', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Robenia Twiddell', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Gilburt Campion', 'solution');
insert into Practica1 (nombre, palabraSecreta) values ('Bealle Brody', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Doralia Pierucci', 'Focused');
insert into Practica1 (nombre, palabraSecreta) values ('Philipa Fynes', 'solution');
insert into Practica1 (nombre, palabraSecreta) values ('Niels Stiant', 'Devolved');
insert into Practica1 (nombre, palabraSecreta) values ('Verile Paulin', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Dionisio Hars', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Robb Pepper', 'foreground');
insert into Practica1 (nombre, palabraSecreta) values ('Gilli Muscroft', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Leshia Sagar', 'Exclusive');
insert into Practica1 (nombre, palabraSecreta) values ('Heinrik Armall', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Rayshell Burnsides', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Jeanne Croall', 'user-facing');
insert into Practica1 (nombre, palabraSecreta) values ('Ros Wippermann', 'Vision-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Gorden Rickarsey', 'Open-architected');
insert into Practica1 (nombre, palabraSecreta) values ('Mariel Sunnucks', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Whitney Haacker', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Joellen Ferryman', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Mitchel Westmoreland', 'system engine');
insert into Practica1 (nombre, palabraSecreta) values ('Carney Desmond', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Sidoney Allred', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Lusa Fass', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Sybyl Cuardall', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Corey Spottiswoode', 'standardization');
insert into Practica1 (nombre, palabraSecreta) values ('Orton Barczewski', 'access');
