insert into Practica1 (nombre, palabraSecreta) values ('Dwayne Maroney', 'Multi-channelled');
insert into Practica1 (nombre, palabraSecreta) values ('Nara Ridel', 'Versatile');
insert into Practica1 (nombre, palabraSecreta) values ('Sylvan Zapata', 'object-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Bale Guiett', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Heindrick Doswell', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Timotheus Gillmor', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Geri Mathan', '4th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Joela Rainer', 'Assimilated');
insert into Practica1 (nombre, palabraSecreta) values ('Kurt Axe', 'dedicated');
insert into Practica1 (nombre, palabraSecreta) values ('Vilhelmina Villar', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Dell Probets', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Cris Mansbridge', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Carlen Hanner', 'leading edge');
insert into Practica1 (nombre, palabraSecreta) values ('Ofilia Wallwork', 'Organic');
insert into Practica1 (nombre, palabraSecreta) values ('Gerri Bassick', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Anatol Poynser', 'Advanced');
insert into Practica1 (nombre, palabraSecreta) values ('Emelia Levinge', 'monitoring');
insert into Practica1 (nombre, palabraSecreta) values ('Oneida McCourtie', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Teodoor Gounot', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Torre Brockbank', 'maximized');
insert into Practica1 (nombre, palabraSecreta) values ('Sarita Shyres', 'Upgradable');
insert into Practica1 (nombre, palabraSecreta) values ('Marrissa Cullington', 'knowledge user');
insert into Practica1 (nombre, palabraSecreta) values ('Ivar Vernay', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Sigismund Wagstaff', 'fault-tolerant');
insert into Practica1 (nombre, palabraSecreta) values ('Diahann Yezafovich', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Arleta Antonoyev', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Stephanus Ajam', 'systematic');
insert into Practica1 (nombre, palabraSecreta) values ('Gwenore Posselt', 'Multi-channelled');
insert into Practica1 (nombre, palabraSecreta) values ('Ellette Brearton', 'matrix');
insert into Practica1 (nombre, palabraSecreta) values ('Alasteir McKnockiter', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Viv Calvard', 'user-facing');
insert into Practica1 (nombre, palabraSecreta) values ('Gonzalo Brilon', 'Assimilated');
insert into Practica1 (nombre, palabraSecreta) values ('Deena Rubinshtein', 'intranet');
insert into Practica1 (nombre, palabraSecreta) values ('Estrella Mallya', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Brig Dorsey', 'bi-directional');
insert into Practica1 (nombre, palabraSecreta) values ('Tonia Dorot', 'incremental');
insert into Practica1 (nombre, palabraSecreta) values ('Aluino Connor', 'Intuitive');
insert into Practica1 (nombre, palabraSecreta) values ('Lidia Phinn', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Appolonia Whitehair', 'Optional');
insert into Practica1 (nombre, palabraSecreta) values ('Sheffield Mabone', 'Profound');
insert into Practica1 (nombre, palabraSecreta) values ('Melitta Renals', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Olly Maud', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Frasier Pleass', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Sada Johnson', 'bandwidth-monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Wilmer Synnott', 'database');
insert into Practica1 (nombre, palabraSecreta) values ('Candis Dorrington', 'Multi-channelled');
insert into Practica1 (nombre, palabraSecreta) values ('Birk Irvine', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Jolie Wigelsworth', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Heinrik Gristock', 'reciprocal');
insert into Practica1 (nombre, palabraSecreta) values ('Norbie Baudrey', 'frame');
insert into Practica1 (nombre, palabraSecreta) values ('Lenci Southby', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Raffaello Caddie', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Karee Kindred', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Jorie De Freyne', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Antonie Perfili', 'human-resource');
insert into Practica1 (nombre, palabraSecreta) values ('Jere Mapholm', 'multimedia');
insert into Practica1 (nombre, palabraSecreta) values ('Jobina Coaten', 'application');
insert into Practica1 (nombre, palabraSecreta) values ('Paxton Levin', 'Inverse');
insert into Practica1 (nombre, palabraSecreta) values ('Jeannie MacNalley', 'artificial intelligence');
insert into Practica1 (nombre, palabraSecreta) values ('Anne Welling', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Alidia Oger', 'Pre-emptive');
insert into Practica1 (nombre, palabraSecreta) values ('Nicolas Lethardy', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Rand Dake', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Eirena Brightling', 'grid-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Bill Battie', 'actuating');
insert into Practica1 (nombre, palabraSecreta) values ('Moyna Cottingham', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Brock Fonzone', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Abrahan Burchmore', 'Fully-configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Tonie Grene', 'Mandatory');
insert into Practica1 (nombre, palabraSecreta) values ('Lionel Lorenzetti', 'monitoring');
insert into Practica1 (nombre, palabraSecreta) values ('Lothaire Stave', 'Grass-roots');
insert into Practica1 (nombre, palabraSecreta) values ('Christie Moreland', 'national');
insert into Practica1 (nombre, palabraSecreta) values ('Mic Spurdens', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Anita Spurdens', 'architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Sumner Wilsone', 'Virtual');
insert into Practica1 (nombre, palabraSecreta) values ('Robbert Boorman', 'Triple-buffered');
insert into Practica1 (nombre, palabraSecreta) values ('Dwayne Lafond', 'analyzer');
insert into Practica1 (nombre, palabraSecreta) values ('Joeann Domotor', 'Profound');
insert into Practica1 (nombre, palabraSecreta) values ('Nani Marquese', 'matrix');
insert into Practica1 (nombre, palabraSecreta) values ('Nathan Pratchett', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Sabine Barthrup', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Ami Georgel', 'methodology');
insert into Practica1 (nombre, palabraSecreta) values ('Jazmin Ferebee', 'policy');
insert into Practica1 (nombre, palabraSecreta) values ('Sarita Puckey', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Corbet Andrasch', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Obie Southward', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Norrie Lanfer', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Renaldo Martinon', 'groupware');
insert into Practica1 (nombre, palabraSecreta) values ('Katrinka Hilldrup', 'uniform');
insert into Practica1 (nombre, palabraSecreta) values ('Lenore Felten', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Isador Jendas', 'frame');
insert into Practica1 (nombre, palabraSecreta) values ('Bel Jasiak', 'Reverse-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Roxi Sorel', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Drake Clayborn', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Orland Vinick', 'De-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Amie Greneham', 'customer loyalty');
insert into Practica1 (nombre, palabraSecreta) values ('Filippo Getsham', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Lisetta Silberschatz', 'Synchronised');
insert into Practica1 (nombre, palabraSecreta) values ('Wynnie Glaves', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Ezekiel Kinchley', 'concept');
insert into Practica1 (nombre, palabraSecreta) values ('Eudora Martensen', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Wini Manhare', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Asa Kardos', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Mateo Girardez', 'Cloned');
insert into Practica1 (nombre, palabraSecreta) values ('Fan Skylett', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Adele Carlisi', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Betsey Grishukov', 'Ameliorated');
insert into Practica1 (nombre, palabraSecreta) values ('Barnaby Bahlmann', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Emilia Fere', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Hussein Heaffey', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Breanne Dobbs', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Noreen Droogan', 'open system');
insert into Practica1 (nombre, palabraSecreta) values ('Sollie Rawcliffe', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Barnabas Aukland', '4th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Jorry Banbrigge', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Dugald Carruthers', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Blayne McKeighen', 'Function-based');
insert into Practica1 (nombre, palabraSecreta) values ('Chico Witchell', 'national');
insert into Practica1 (nombre, palabraSecreta) values ('Peder Cuerdale', 'incremental');
insert into Practica1 (nombre, palabraSecreta) values ('Doralin Elson', 'reciprocal');
insert into Practica1 (nombre, palabraSecreta) values ('Calhoun McNeill', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Dari Cruxton', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Holly-anne Crocken', 'methodology');
insert into Practica1 (nombre, palabraSecreta) values ('Ashlee Byart', 'Inverse');
insert into Practica1 (nombre, palabraSecreta) values ('Suzi Odda', 'adapter');
insert into Practica1 (nombre, palabraSecreta) values ('Kalindi Shay', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Noak Wilfinger', 'conglomeration');
insert into Practica1 (nombre, palabraSecreta) values ('Cornelia Sellick', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Ava Scholfield', 'Reactive');
insert into Practica1 (nombre, palabraSecreta) values ('Sheelagh Esberger', 'product');
insert into Practica1 (nombre, palabraSecreta) values ('Kikelia Arenson', 'Networked');
insert into Practica1 (nombre, palabraSecreta) values ('Dana Colt', 'time-frame');
insert into Practica1 (nombre, palabraSecreta) values ('Roy Tudor', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Alvina Maylor', 'hub');
insert into Practica1 (nombre, palabraSecreta) values ('Corrianne Braz', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Mallissa Fundell', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Trista Fatharly', 'policy');
insert into Practica1 (nombre, palabraSecreta) values ('Rad Tayt', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Arnie Oldnall', 'help-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Redd Burchill', 'uniform');
insert into Practica1 (nombre, palabraSecreta) values ('Adela Nary', 'Cross-group');
insert into Practica1 (nombre, palabraSecreta) values ('Brigham Attwater', 'Assimilated');
insert into Practica1 (nombre, palabraSecreta) values ('Libby Hammerberger', 'concept');
insert into Practica1 (nombre, palabraSecreta) values ('Quentin Kik', 'time-frame');
insert into Practica1 (nombre, palabraSecreta) values ('Dannie Puddephatt', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Rebeca Rickets', 'synergy');
insert into Practica1 (nombre, palabraSecreta) values ('Kenny Casperri', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Hermon Pagel', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Nancey Baumford', 'open architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Armando Dudleston', 'Cloned');
insert into Practica1 (nombre, palabraSecreta) values ('Bearnard Buddock', 'matrix');
insert into Practica1 (nombre, palabraSecreta) values ('Hartley Rosenfelt', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Alvy Kensit', 'De-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Ethe Groves', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Marcela Benoit', 'upward-trending');
insert into Practica1 (nombre, palabraSecreta) values ('Gene Doles', 'architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Renee Beldon', 'Profound');
insert into Practica1 (nombre, palabraSecreta) values ('Gwenora Comiam', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Pier Shrive', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Barney Haslewood', 'well-modulated');
insert into Practica1 (nombre, palabraSecreta) values ('Vail Balentyne', 'customer loyalty');
insert into Practica1 (nombre, palabraSecreta) values ('Lizzy Joannet', 'bifurcated');
insert into Practica1 (nombre, palabraSecreta) values ('Tadeas Swindells', 'User-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Gabbie Scandrite', 'Organized');
insert into Practica1 (nombre, palabraSecreta) values ('Natka Yorath', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Shurlock Ghioni', 'Face to face');
insert into Practica1 (nombre, palabraSecreta) values ('Deeann Mattingson', 'instruction set');
insert into Practica1 (nombre, palabraSecreta) values ('Casar Naerup', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Andree Sutch', 'frame');
insert into Practica1 (nombre, palabraSecreta) values ('Dosi Creech', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Merrick Banbrook', 'high-level');
insert into Practica1 (nombre, palabraSecreta) values ('Eden Lowin', 'mission-critical');
insert into Practica1 (nombre, palabraSecreta) values ('Rhona Thys', 'Function-based');
insert into Practica1 (nombre, palabraSecreta) values ('Leonelle Elwel', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Matelda Mariot', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Gearalt Witsey', 'Business-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Selinda Hardison', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Pip Cornes', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Eberto Fowlds', 'focus group');
insert into Practica1 (nombre, palabraSecreta) values ('Vivyanne Appleford', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Annamaria Checklin', 'open architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Costanza Mortlock', 'Intuitive');
insert into Practica1 (nombre, palabraSecreta) values ('Lorena De Gouy', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Erina Tembey', 'functionalities');
insert into Practica1 (nombre, palabraSecreta) values ('Kristan Playhill', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Northrup Gothup', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Kai Chrichton', 'Triple-buffered');
insert into Practica1 (nombre, palabraSecreta) values ('Marie-ann Noe', 'empowering');
insert into Practica1 (nombre, palabraSecreta) values ('Georgena Buntin', 'analyzer');
insert into Practica1 (nombre, palabraSecreta) values ('Jessamyn Farny', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Feodor Jedrych', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Alica Burston', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Selia Scimone', 'even-keeled');
insert into Practica1 (nombre, palabraSecreta) values ('Fanchette McKinney', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Allix Mattheis', 'Diverse');
insert into Practica1 (nombre, palabraSecreta) values ('Annabella Biles', 'well-modulated');
insert into Practica1 (nombre, palabraSecreta) values ('Pace Gansbuhler', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Giuseppe Spataro', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Jeramey Broadhurst', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Marcello Sheardown', 'database');
insert into Practica1 (nombre, palabraSecreta) values ('Abraham Kubin', 'responsive');
insert into Practica1 (nombre, palabraSecreta) values ('Reid Kingdon', 'functionalities');
insert into Practica1 (nombre, palabraSecreta) values ('Rancell Vermer', 'utilisation');
insert into Practica1 (nombre, palabraSecreta) values ('Shannon Checchi', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Gonzales Storrar', 'data-warehouse');
insert into Practica1 (nombre, palabraSecreta) values ('Obadias Boyse', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Jerrilyn Testro', 'Synergized');
insert into Practica1 (nombre, palabraSecreta) values ('Pierre Comini', 'Open-source');
insert into Practica1 (nombre, palabraSecreta) values ('Fanechka McGawn', 'impactful');
insert into Practica1 (nombre, palabraSecreta) values ('Tim Guerin', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Barbee Poter', 'flexibility');
insert into Practica1 (nombre, palabraSecreta) values ('Ramonda Piken', 'Proactive');
insert into Practica1 (nombre, palabraSecreta) values ('Darrick Prudence', 'open architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Gerhard Boatwright', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Brett Winsiowiecki', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Nerti Lock', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Brod Mudie', 'Mandatory');
insert into Practica1 (nombre, palabraSecreta) values ('Adan Guage', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Eberhard Pieper', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Welch Isabell', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Quentin Fone', 'systematic');
insert into Practica1 (nombre, palabraSecreta) values ('Willdon Bernot', '6th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Bastian Stanworth', 'frame');
insert into Practica1 (nombre, palabraSecreta) values ('Woodman Pau', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Knox Oakenfall', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Anet Deaville', 'bifurcated');
insert into Practica1 (nombre, palabraSecreta) values ('Bibbie Naile', 'algorithm');
insert into Practica1 (nombre, palabraSecreta) values ('Kellyann Arstall', 'methodical');
insert into Practica1 (nombre, palabraSecreta) values ('Darci Silbert', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Gillie Muckley', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Daria Goodbody', 'workforce');
insert into Practica1 (nombre, palabraSecreta) values ('Errol Kiss', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Chantalle Prandoni', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Codie Feehan', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Dan Kunes', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Gretta Haeslier', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Adina Hoffman', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Arvy Coats', 'mobile');
insert into Practica1 (nombre, palabraSecreta) values ('Davidde Vasilyonok', 'Expanded');
insert into Practica1 (nombre, palabraSecreta) values ('Rodrique Tolan', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Innis Soles', 'Expanded');
insert into Practica1 (nombre, palabraSecreta) values ('Ferrel Birtwistle', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Ethelin Muehler', 'open system');
insert into Practica1 (nombre, palabraSecreta) values ('Cheri Seabright', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Elfrida Bambridge', 'Switchable');
insert into Practica1 (nombre, palabraSecreta) values ('Charyl Beeze', 'attitude-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Eva Reely', 'application');
insert into Practica1 (nombre, palabraSecreta) values ('Alisha Karchowski', 'Profound');
insert into Practica1 (nombre, palabraSecreta) values ('Harry Lebbern', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Darnall Capaldo', 'Open-architected');
insert into Practica1 (nombre, palabraSecreta) values ('Jasen Sayes', 'Diverse');
insert into Practica1 (nombre, palabraSecreta) values ('Libbie Ganiclef', 'circuit');
insert into Practica1 (nombre, palabraSecreta) values ('Liliane Rockcliff', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Correy Youngman', 'Multi-lateral');
insert into Practica1 (nombre, palabraSecreta) values ('Ulrika Wilkerson', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Edith Vasilov', 'utilisation');
insert into Practica1 (nombre, palabraSecreta) values ('Gretna Geeson', 'instruction set');
insert into Practica1 (nombre, palabraSecreta) values ('Nester Nurdin', 'conglomeration');
insert into Practica1 (nombre, palabraSecreta) values ('Gloriana Rittelmeyer', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Lem Bowmer', 'Multi-tiered');
insert into Practica1 (nombre, palabraSecreta) values ('Ahmed Castlake', 'dedicated');
insert into Practica1 (nombre, palabraSecreta) values ('Dorrie Gellett', 'context-sensitive');
insert into Practica1 (nombre, palabraSecreta) values ('Maddy Vaudrey', 'Diverse');
insert into Practica1 (nombre, palabraSecreta) values ('Arabel Vermer', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Gardner Alliberton', 'background');
insert into Practica1 (nombre, palabraSecreta) values ('Omar Ebbutt', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Magdalena Gilley', 'heuristic');
insert into Practica1 (nombre, palabraSecreta) values ('Cyb Eckhard', 'interface');
insert into Practica1 (nombre, palabraSecreta) values ('Ogdan MacAllen', 'Robust');
insert into Practica1 (nombre, palabraSecreta) values ('Marjory Cabel', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Rollo Mangion', 'instruction set');
insert into Practica1 (nombre, palabraSecreta) values ('Enrica Brownsell', 'Business-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Ethe Burdin', 'high-level');
insert into Practica1 (nombre, palabraSecreta) values ('Avril Landall', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Osbourn Spellacey', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Douglass Hefferan', 'Self-enabling');
insert into Practica1 (nombre, palabraSecreta) values ('Tulley Sign', 'application');
insert into Practica1 (nombre, palabraSecreta) values ('Drugi Deerness', 'eco-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Randi O''Grady', 'portal');
insert into Practica1 (nombre, palabraSecreta) values ('Lane Forestall', 'Multi-tiered');
insert into Practica1 (nombre, palabraSecreta) values ('Derry Church', 'bifurcated');
insert into Practica1 (nombre, palabraSecreta) values ('Desmund Skerman', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Burl Rowledge', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Lawton Starton', 'Assimilated');
insert into Practica1 (nombre, palabraSecreta) values ('Emmalynn Deluca', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Wang Lander', 'artificial intelligence');
insert into Practica1 (nombre, palabraSecreta) values ('Crysta Bontine', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Nicky Thaxter', 'forecast');
insert into Practica1 (nombre, palabraSecreta) values ('Quincy Giurio', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Marilyn Miquelet', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Wesley Painten', 'initiative');
insert into Practica1 (nombre, palabraSecreta) values ('Janel Tincknell', 'help-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Sinclare Comettoi', 'Sharable');
insert into Practica1 (nombre, palabraSecreta) values ('Lorenza Crawley', 'toolset');
insert into Practica1 (nombre, palabraSecreta) values ('Aldridge Worsell', 'intermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Torry Dolden', 'architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Gweneth Matousek', 'intermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Annalise Mulford', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Cristine Clutheram', '4th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Riva Reedie', 'upward-trending');
insert into Practica1 (nombre, palabraSecreta) values ('Sari Gieraths', 'heuristic');
insert into Practica1 (nombre, palabraSecreta) values ('Jobyna Punshon', 'matrix');
insert into Practica1 (nombre, palabraSecreta) values ('Daryn Slaughter', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Artemus Labone', 'Customizable');
insert into Practica1 (nombre, palabraSecreta) values ('Leia Till', 'archive');
insert into Practica1 (nombre, palabraSecreta) values ('Gustave Natalie', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Ranee Rojas', 'cohesive');
insert into Practica1 (nombre, palabraSecreta) values ('Sophronia Banbridge', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Darren Berka', 'Down-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Lynnet Rigard', 'local');
insert into Practica1 (nombre, palabraSecreta) values ('Desmond Oxbury', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Ninette Elmhirst', 'web-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Kendra Willson', 'dynamic');
insert into Practica1 (nombre, palabraSecreta) values ('Morrie Toffolo', 'function');
insert into Practica1 (nombre, palabraSecreta) values ('Micaela Ambrozewicz', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Rockey Gossart', 'internet solution');
insert into Practica1 (nombre, palabraSecreta) values ('Sarina Ortes', 'superstructure');
insert into Practica1 (nombre, palabraSecreta) values ('Amby Yearns', 'Devolved');
insert into Practica1 (nombre, palabraSecreta) values ('Ileana Beddows', 'Cross-platform');
insert into Practica1 (nombre, palabraSecreta) values ('Katti Askam', 'circuit');
insert into Practica1 (nombre, palabraSecreta) values ('Alleyn Wolseley', 'grid-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Aloin Hargreave', 'needs-based');
insert into Practica1 (nombre, palabraSecreta) values ('Jilli Pocknell', 'extranet');
insert into Practica1 (nombre, palabraSecreta) values ('Latashia Ouslem', 'client-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Anderea Fussie', 'actuating');
insert into Practica1 (nombre, palabraSecreta) values ('Forrester Coller', 'data-warehouse');
insert into Practica1 (nombre, palabraSecreta) values ('Nonnah Hallgate', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Kiley Maccrea', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Cecile Testro', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Abigail Pitfield', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Ruttger Edmondson', 'Adaptive');
insert into Practica1 (nombre, palabraSecreta) values ('Kean Keasey', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Janis Nappin', 'context-sensitive');
insert into Practica1 (nombre, palabraSecreta) values ('Gustav Grenshiels', 'systematic');
insert into Practica1 (nombre, palabraSecreta) values ('Vladamir Greasty', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Reginald Woodroofe', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Bette-ann Fry', 'zero defect');
insert into Practica1 (nombre, palabraSecreta) values ('Niles de Verson', 'Re-contextualized');
insert into Practica1 (nombre, palabraSecreta) values ('Juliann Botten', 'Cross-group');
insert into Practica1 (nombre, palabraSecreta) values ('Halley Strangeways', 'regional');
insert into Practica1 (nombre, palabraSecreta) values ('Crystie Queste', 'actuating');
insert into Practica1 (nombre, palabraSecreta) values ('Jackie Darte', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Skipper Brunelleschi', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Natalee Been', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Cristina Silverlock', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Kerrie Cosser', 'internet solution');
insert into Practica1 (nombre, palabraSecreta) values ('Gladys Cursons', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Gayel Dreossi', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Arabele Rozzell', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Herb Macia', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Wilden Terzi', 'Profound');
insert into Practica1 (nombre, palabraSecreta) values ('Valenka Soulsby', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Monti Ghest', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Tatum Sleeman', 'product');
insert into Practica1 (nombre, palabraSecreta) values ('Nealson Bunyard', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Tillie Attoe', 'multi-tasking');
insert into Practica1 (nombre, palabraSecreta) values ('Griffy Gilpillan', 'actuating');
insert into Practica1 (nombre, palabraSecreta) values ('Nefen Zannotelli', 'attitude');
insert into Practica1 (nombre, palabraSecreta) values ('Roosevelt Whitlaw', 'Intuitive');
insert into Practica1 (nombre, palabraSecreta) values ('Rebekah Vynoll', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Leda Partlett', 'artificial intelligence');
insert into Practica1 (nombre, palabraSecreta) values ('Rosemonde Kestian', 'user-facing');
insert into Practica1 (nombre, palabraSecreta) values ('Verla Cunningham', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Jocelyne Corder', 'methodology');
insert into Practica1 (nombre, palabraSecreta) values ('Sibylla MacDowal', 'circuit');
insert into Practica1 (nombre, palabraSecreta) values ('Clementina Doerling', 'Pre-emptive');
insert into Practica1 (nombre, palabraSecreta) values ('Steven Gettone', 'Adaptive');
insert into Practica1 (nombre, palabraSecreta) values ('Matthew Oddboy', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Eleanora Dumbrill', 'support');
insert into Practica1 (nombre, palabraSecreta) values ('Itch Ferron', 'Seamless');
insert into Practica1 (nombre, palabraSecreta) values ('Neala Reignard', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Randi Claypole', 'local');
insert into Practica1 (nombre, palabraSecreta) values ('Jamima Abrahams', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Wilhelmina Eglin', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Gustie Bearham', 'software');
insert into Practica1 (nombre, palabraSecreta) values ('Che Grayshan', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Dorie Sarch', 'Universal');
insert into Practica1 (nombre, palabraSecreta) values ('Arturo Hurst', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Brice Rought', 'Multi-tiered');
insert into Practica1 (nombre, palabraSecreta) values ('Martin Vasey', 'stable');
insert into Practica1 (nombre, palabraSecreta) values ('Durward Bartolomeoni', 'dynamic');
insert into Practica1 (nombre, palabraSecreta) values ('Michelle Stuckey', 'throughput');
insert into Practica1 (nombre, palabraSecreta) values ('Cassie Stolworthy', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Anet Le land', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Lottie Besque', 'capability');
insert into Practica1 (nombre, palabraSecreta) values ('Edsel Middleton', 'transitional');
insert into Practica1 (nombre, palabraSecreta) values ('Darda Golborne', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Johnna Capelow', 'Configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Sigismondo MacGhee', 'algorithm');
insert into Practica1 (nombre, palabraSecreta) values ('Brandais Liquorish', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Philip Rattery', 'Diverse');
insert into Practica1 (nombre, palabraSecreta) values ('Westleigh Chevin', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Gun Wallwood', 'data-warehouse');
insert into Practica1 (nombre, palabraSecreta) values ('Amber Harnett', 'support');
insert into Practica1 (nombre, palabraSecreta) values ('Cory Northridge', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Arleta Buzin', 'Synergistic');
insert into Practica1 (nombre, palabraSecreta) values ('Corenda Dorset', 'bi-directional');
insert into Practica1 (nombre, palabraSecreta) values ('Bord Montez', 'data-warehouse');
insert into Practica1 (nombre, palabraSecreta) values ('Trescha Klain', 'extranet');
insert into Practica1 (nombre, palabraSecreta) values ('Shayne Sertin', 'directional');
insert into Practica1 (nombre, palabraSecreta) values ('Salomi Doiley', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Orelia Jery', 'directional');
insert into Practica1 (nombre, palabraSecreta) values ('Salaidh Jess', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Oriana Meadowcraft', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Maxy Lear', 'stable');
insert into Practica1 (nombre, palabraSecreta) values ('Trever Rodinger', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Arvin Lydster', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Gunilla Shadwick', 'success');
insert into Practica1 (nombre, palabraSecreta) values ('Otes Quarrell', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Marie Sofe', 'regional');
insert into Practica1 (nombre, palabraSecreta) values ('Nicol Mingey', 'Reverse-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Onofredo Denekamp', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Celestia Buckam', 'solution-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Lucky Gwillyam', 'Integrated');
insert into Practica1 (nombre, palabraSecreta) values ('Trula Tregenna', 'extranet');
insert into Practica1 (nombre, palabraSecreta) values ('Tudor Sampey', 'Focused');
insert into Practica1 (nombre, palabraSecreta) values ('Tadeo Olsen', 'Innovative');
insert into Practica1 (nombre, palabraSecreta) values ('Quintus Dilliway', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Bree Crownshaw', 'systemic');
insert into Practica1 (nombre, palabraSecreta) values ('Robenia Alvis', 'responsive');
insert into Practica1 (nombre, palabraSecreta) values ('Dalis Hacard', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Rosana Mainz', 'installation');
insert into Practica1 (nombre, palabraSecreta) values ('Zacharia Chipchase', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Minerva Tschierasche', 'Networked');
insert into Practica1 (nombre, palabraSecreta) values ('Melloney Sharvill', 'transitional');
insert into Practica1 (nombre, palabraSecreta) values ('Yulma Edens', 'Stand-alone');
insert into Practica1 (nombre, palabraSecreta) values ('Hi Thurlow', 'Organized');
insert into Practica1 (nombre, palabraSecreta) values ('Damon Wheatcroft', 'Organized');
insert into Practica1 (nombre, palabraSecreta) values ('Perla Davidsen', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Elena Gaskin', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Maryjane Colhoun', 'Business-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Marcelline Ducham', 'pricing structure');
insert into Practica1 (nombre, palabraSecreta) values ('Bax Sinden', 'Vision-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Joelie Whiles', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Halli Saing', 'hierarchy');
insert into Practica1 (nombre, palabraSecreta) values ('Vanny Delcastel', 'standardization');
insert into Practica1 (nombre, palabraSecreta) values ('Josephine Eschalette', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Shari Domino', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Dillie Roddick', 'Diverse');
insert into Practica1 (nombre, palabraSecreta) values ('Harwell Westmore', 'eco-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Eugenie Littlepage', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Fayth Corre', 'Polarised');
insert into Practica1 (nombre, palabraSecreta) values ('Elsy Grigor', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Turner Roseborough', 'Grass-roots');
insert into Practica1 (nombre, palabraSecreta) values ('Simeon Ruf', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Yvon Davidescu', 'even-keeled');
insert into Practica1 (nombre, palabraSecreta) values ('Fritz Allridge', 'static');
insert into Practica1 (nombre, palabraSecreta) values ('Avery Flucker', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Cathyleen Godlip', 'Operative');
insert into Practica1 (nombre, palabraSecreta) values ('Cletus Allanson', 'access');
insert into Practica1 (nombre, palabraSecreta) values ('Blondell Ferrarone', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Gilly Wilcocks', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Tito Stapele', 'Devolved');
insert into Practica1 (nombre, palabraSecreta) values ('Lek Lauridsen', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Byrom Warke', 'knowledge base');
insert into Practica1 (nombre, palabraSecreta) values ('Valentino Carvilla', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Levi Boatman', 'concept');
insert into Practica1 (nombre, palabraSecreta) values ('Eddy Haily', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Allayne Mushrow', 'needs-based');
insert into Practica1 (nombre, palabraSecreta) values ('Alena Dooland', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Archibold East', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Eleen Bradborne', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Giusto Wilshin', 'systematic');
insert into Practica1 (nombre, palabraSecreta) values ('Raychel Rehorek', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Lutero Axton', 'hub');
insert into Practica1 (nombre, palabraSecreta) values ('Carlos Quernel', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Beilul Keilty', 'implementation');
insert into Practica1 (nombre, palabraSecreta) values ('Susanna Dutch', 'Adaptive');
insert into Practica1 (nombre, palabraSecreta) values ('Stanford Hopfner', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Sherwood Zylbermann', 'Up-sized');
insert into Practica1 (nombre, palabraSecreta) values ('Federica Reynoollds', 'eco-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Waylan Hiorn', 'Triple-buffered');
insert into Practica1 (nombre, palabraSecreta) values ('Rodolfo Beevens', 'focus group');
insert into Practica1 (nombre, palabraSecreta) values ('Esra Cobb', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Garrik Vedekhin', 'fault-tolerant');
insert into Practica1 (nombre, palabraSecreta) values ('Melody McGriele', 'Enhanced');
insert into Practica1 (nombre, palabraSecreta) values ('Tull Kuhle', 'clear-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Jozef Birwhistle', 'collaboration');
insert into Practica1 (nombre, palabraSecreta) values ('Jodi Camings', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Ximenez Athersmith', 'Monitored');
insert into Practica1 (nombre, palabraSecreta) values ('Roley Diss', 'directional');
insert into Practica1 (nombre, palabraSecreta) values ('Windy Cornelisse', 'portal');
insert into Practica1 (nombre, palabraSecreta) values ('Pall Valadez', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Esta Gatrell', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Corry Powis', 'time-frame');
insert into Practica1 (nombre, palabraSecreta) values ('Chicky Gauch', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Emlynn Tomblings', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Clevey Ballay', 'disintermediate');
insert into Practica1 (nombre, palabraSecreta) values ('Ody Gulland', 'Configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Fleurette Yarrall', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Herbie Lackham', 'groupware');
insert into Practica1 (nombre, palabraSecreta) values ('Shaylah Igglesden', 'service-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Lorelei Lakenton', 'Adaptive');
insert into Practica1 (nombre, palabraSecreta) values ('Archambault Delacote', 'Expanded');
insert into Practica1 (nombre, palabraSecreta) values ('Kinna Dorman', 'object-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Kirk Huddlestone', 'utilisation');
insert into Practica1 (nombre, palabraSecreta) values ('Jan Lowndsbrough', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Susanna Cathery', '5th generation');
insert into Practica1 (nombre, palabraSecreta) values ('Marion Hebron', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Mandi Adnet', 'dedicated');
insert into Practica1 (nombre, palabraSecreta) values ('Renado Hackley', 'empowering');
insert into Practica1 (nombre, palabraSecreta) values ('Gannie Osborne', 'web-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Abbe De Gregoli', 'orchestration');
insert into Practica1 (nombre, palabraSecreta) values ('Desiree Shemilt', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Athena Saberton', 'logistical');
insert into Practica1 (nombre, palabraSecreta) values ('Nadeen Llewellen', 'Customer-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Liva Mullan', 'internet solution');
insert into Practica1 (nombre, palabraSecreta) values ('Abbi Buckberry', 'tertiary');
insert into Practica1 (nombre, palabraSecreta) values ('Enrichetta Izatt', 'Inverse');
insert into Practica1 (nombre, palabraSecreta) values ('Freda Bunkle', 'Business-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Rebe Loram', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Hyacinthe Sille', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Ezri Bebb', 'interface');
insert into Practica1 (nombre, palabraSecreta) values ('Tallie Rapaport', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Jermayne Redan', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Willis Housaman', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Dirk Cowins', 'web-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Inglis Petrovsky', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Adrianne Lurriman', 'task-force');
insert into Practica1 (nombre, palabraSecreta) values ('Rudyard Mundle', 'functionalities');
insert into Practica1 (nombre, palabraSecreta) values ('Celeste Handman', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Justine O''Sherin', 'multi-state');
insert into Practica1 (nombre, palabraSecreta) values ('Rochester Ragbourne', 'Synergistic');
insert into Practica1 (nombre, palabraSecreta) values ('Konstanze Farfalameev', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Dru Bettenay', 'hub');
insert into Practica1 (nombre, palabraSecreta) values ('Leese Potte', 'architecture');
insert into Practica1 (nombre, palabraSecreta) values ('Ennis McRamsey', 'hierarchy');
insert into Practica1 (nombre, palabraSecreta) values ('Arlana Collen', 'eco-centric');
insert into Practica1 (nombre, palabraSecreta) values ('Bevin Adamovich', 'Streamlined');
insert into Practica1 (nombre, palabraSecreta) values ('Sayers Howgego', 'executive');
insert into Practica1 (nombre, palabraSecreta) values ('Ted Coopey', 'global');
insert into Practica1 (nombre, palabraSecreta) values ('Inness Rieger', 'Function-based');
insert into Practica1 (nombre, palabraSecreta) values ('Rolland Tarbet', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Oneida Lakin', 'Extended');
insert into Practica1 (nombre, palabraSecreta) values ('Rici Elcox', 'encryption');
insert into Practica1 (nombre, palabraSecreta) values ('Godiva Petrelli', 'productivity');
insert into Practica1 (nombre, palabraSecreta) values ('Marcelia Reede', 'workforce');
insert into Practica1 (nombre, palabraSecreta) values ('Deborah Smyth', 'maximized');
insert into Practica1 (nombre, palabraSecreta) values ('Nata Enriquez', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Hurleigh Pietroni', 'throughput');
insert into Practica1 (nombre, palabraSecreta) values ('Dora Arni', 'hybrid');
insert into Practica1 (nombre, palabraSecreta) values ('Glen Danet', 'discrete');
insert into Practica1 (nombre, palabraSecreta) values ('Ivar Kyle', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Val Meaker', 'coherent');
insert into Practica1 (nombre, palabraSecreta) values ('Zak Ible', 'human-resource');
insert into Practica1 (nombre, palabraSecreta) values ('Willi Villalta', 'groupware');
insert into Practica1 (nombre, palabraSecreta) values ('Grissel Iacovino', 'solution-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Rayner Britee', 'intangible');
insert into Practica1 (nombre, palabraSecreta) values ('Mitch Chatband', 'bifurcated');
insert into Practica1 (nombre, palabraSecreta) values ('Wilow McGonagle', 'secured line');
insert into Practica1 (nombre, palabraSecreta) values ('Constantine Tommaseo', 'knowledge user');
insert into Practica1 (nombre, palabraSecreta) values ('Goraud Eagle', 'portal');
insert into Practica1 (nombre, palabraSecreta) values ('Mal Minard', 'local area network');
insert into Practica1 (nombre, palabraSecreta) values ('Eartha Avory', 'hub');
insert into Practica1 (nombre, palabraSecreta) values ('Chaddy Quinney', 'framework');
insert into Practica1 (nombre, palabraSecreta) values ('Josephine Demougeot', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Brana Adolthine', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Bryan Braniff', 'intranet');
insert into Practica1 (nombre, palabraSecreta) values ('Lars Giraudy', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Jacki Pryell', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Sebastien Copins', 'Reduced');
insert into Practica1 (nombre, palabraSecreta) values ('Randal Novichenko', 'parallelism');
insert into Practica1 (nombre, palabraSecreta) values ('Brinna Kedie', 'real-time');
insert into Practica1 (nombre, palabraSecreta) values ('Darwin Dongate', 'challenge');
insert into Practica1 (nombre, palabraSecreta) values ('Staci Gadsby', 'executive');
insert into Practica1 (nombre, palabraSecreta) values ('Neely Babbs', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Teresina Keen', 'Inverse');
insert into Practica1 (nombre, palabraSecreta) values ('Lorna Punch', 'background');
insert into Practica1 (nombre, palabraSecreta) values ('Wolfy Langton', 'Enhanced');
insert into Practica1 (nombre, palabraSecreta) values ('Delphine Pinyon', 'time-frame');
insert into Practica1 (nombre, palabraSecreta) values ('Jesse Lackner', 'tangible');
insert into Practica1 (nombre, palabraSecreta) values ('Jorey Attenburrow', 'fresh-thinking');
insert into Practica1 (nombre, palabraSecreta) values ('Lilla Mattiuzzi', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Albie Winspur', 'Proactive');
insert into Practica1 (nombre, palabraSecreta) values ('Archer Herley', 'Implemented');
insert into Practica1 (nombre, palabraSecreta) values ('Andra Ruby', 'concept');
insert into Practica1 (nombre, palabraSecreta) values ('Julianna Dils', 'Business-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Anna Beak', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Annalise Petru', 'context-sensitive');
insert into Practica1 (nombre, palabraSecreta) values ('Andeee Eversley', 'Intuitive');
insert into Practica1 (nombre, palabraSecreta) values ('Eleni Coulson', 'algorithm');
insert into Practica1 (nombre, palabraSecreta) values ('Lanette Joliffe', 'leverage');
insert into Practica1 (nombre, palabraSecreta) values ('Fay Butteris', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Bekki Puttock', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Gerik Youles', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Giselbert Grouvel', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Alysia Pauwel', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Myles Fumagall', 'modular');
insert into Practica1 (nombre, palabraSecreta) values ('Bendix Van der Son', 'internet solution');
insert into Practica1 (nombre, palabraSecreta) values ('Josh Hanner', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Giselle Manvelle', 'Secured');
insert into Practica1 (nombre, palabraSecreta) values ('Sibyl Crank', 'Multi-layered');
insert into Practica1 (nombre, palabraSecreta) values ('Milo Kliemke', 'Front-line');
insert into Practica1 (nombre, palabraSecreta) values ('Nicolai Matignon', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Dewitt Hart', 'methodology');
insert into Practica1 (nombre, palabraSecreta) values ('Louise McShee', 'solution-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Juanita Doll', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Joel Stanier', 'Devolved');
insert into Practica1 (nombre, palabraSecreta) values ('Bentlee Augustus', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Arlene Braxay', 'conglomeration');
insert into Practica1 (nombre, palabraSecreta) values ('Fredi Maud', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Clemens Coldbathe', 'Automated');
insert into Practica1 (nombre, palabraSecreta) values ('Alysa Burbank', 'Open-source');
insert into Practica1 (nombre, palabraSecreta) values ('Niels Andric', 'actuating');
insert into Practica1 (nombre, palabraSecreta) values ('Edyth Keirl', 'Organic');
insert into Practica1 (nombre, palabraSecreta) values ('Leshia Straine', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Kai Twinborough', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Lewie Dufton', 'time-frame');
insert into Practica1 (nombre, palabraSecreta) values ('Iona Wildbore', 'contextually-based');
insert into Practica1 (nombre, palabraSecreta) values ('Tandie Gieraths', 'Innovative');
insert into Practica1 (nombre, palabraSecreta) values ('Christel Pealing', 'even-keeled');
insert into Practica1 (nombre, palabraSecreta) values ('Torr Milthorpe', 'responsive');
insert into Practica1 (nombre, palabraSecreta) values ('Tracee Furmonger', '24/7');
insert into Practica1 (nombre, palabraSecreta) values ('Arielle Newlands', 'Seamless');
insert into Practica1 (nombre, palabraSecreta) values ('Emilio Freeland', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Silvie Adamo', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Kameko Mathew', 'Exclusive');
insert into Practica1 (nombre, palabraSecreta) values ('Tova Kamiyama', 'Persevering');
insert into Practica1 (nombre, palabraSecreta) values ('Anallise Eshelby', 'ability');
insert into Practica1 (nombre, palabraSecreta) values ('Woodie Jagger', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Renee Flux', 'Quality-focused');
insert into Practica1 (nombre, palabraSecreta) values ('Cole Pinke', 'Programmable');
insert into Practica1 (nombre, palabraSecreta) values ('Jannelle Trimnell', 'Team-oriented');
insert into Practica1 (nombre, palabraSecreta) values ('Lin Casari', 'Horizontal');
insert into Practica1 (nombre, palabraSecreta) values ('Terri Maffioletti', 'contingency');
insert into Practica1 (nombre, palabraSecreta) values ('Adam Sussems', 'Front-line');
insert into Practica1 (nombre, palabraSecreta) values ('Mathilda Pickle', 'Synergized');
insert into Practica1 (nombre, palabraSecreta) values ('Noble Eddow', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Sandy Readshall', 'capacity');
insert into Practica1 (nombre, palabraSecreta) values ('Sula Ebbutt', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Reese Dormon', 'Extended');
insert into Practica1 (nombre, palabraSecreta) values ('Maryann Caile', 'forecast');
insert into Practica1 (nombre, palabraSecreta) values ('Kermie Lillie', 'zero administration');
insert into Practica1 (nombre, palabraSecreta) values ('Frederico Andrivot', 'Innovative');
insert into Practica1 (nombre, palabraSecreta) values ('Lilian Bamblett', 'Organic');
insert into Practica1 (nombre, palabraSecreta) values ('Ashlan Ivasechko', 'interactive');
insert into Practica1 (nombre, palabraSecreta) values ('Mauricio Hagston', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Lorraine Touson', 'incremental');
insert into Practica1 (nombre, palabraSecreta) values ('Denise Vinck', 'impactful');
insert into Practica1 (nombre, palabraSecreta) values ('Torey Scotland', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Matthus Polack', 'alliance');
insert into Practica1 (nombre, palabraSecreta) values ('Stoddard Nekrews', 'Front-line');
insert into Practica1 (nombre, palabraSecreta) values ('Claudette Wisher', 'Seamless');
insert into Practica1 (nombre, palabraSecreta) values ('Whittaker Mardell', 'product');
insert into Practica1 (nombre, palabraSecreta) values ('Woody Heading', 'matrix');
insert into Practica1 (nombre, palabraSecreta) values ('Heywood Glasspool', 'Face to face');
insert into Practica1 (nombre, palabraSecreta) values ('Ginger Shillaber', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Jenica Skitteral', 'functionalities');
insert into Practica1 (nombre, palabraSecreta) values ('Mirna Haddy', 'Function-based');
insert into Practica1 (nombre, palabraSecreta) values ('Breanne Casini', 'composite');
insert into Practica1 (nombre, palabraSecreta) values ('Fanchette Cucinotta', 'Graphical User Interface');
insert into Practica1 (nombre, palabraSecreta) values ('Cyrille Tanslie', 'leverage');
insert into Practica1 (nombre, palabraSecreta) values ('Alexia Ive', 'Centralized');
insert into Practica1 (nombre, palabraSecreta) values ('Fee O''Doran', 'zero defect');
insert into Practica1 (nombre, palabraSecreta) values ('Grethel Bruin', 'hierarchy');
insert into Practica1 (nombre, palabraSecreta) values ('Hermy Chaudret', 'Organic');
insert into Practica1 (nombre, palabraSecreta) values ('Karissa Mc Andrew', 'Optimized');
insert into Practica1 (nombre, palabraSecreta) values ('Dedra Tattersdill', 'infrastructure');
insert into Practica1 (nombre, palabraSecreta) values ('Randolf Manie', 'neural-net');
insert into Practica1 (nombre, palabraSecreta) values ('Stace Di Angelo', 'Managed');
insert into Practica1 (nombre, palabraSecreta) values ('Lynne Levings', 'strategy');
insert into Practica1 (nombre, palabraSecreta) values ('Kermy Helstrom', 'responsive');
insert into Practica1 (nombre, palabraSecreta) values ('Kristofer Romayn', 'Networked');
insert into Practica1 (nombre, palabraSecreta) values ('Lolita Pudan', 'non-volatile');
insert into Practica1 (nombre, palabraSecreta) values ('Zsa zsa Witchalls', 'Multi-tiered');
insert into Practica1 (nombre, palabraSecreta) values ('Barrie Crofthwaite', 'attitude');
insert into Practica1 (nombre, palabraSecreta) values ('Desirae Pauncefort', 'scalable');
insert into Practica1 (nombre, palabraSecreta) values ('Natasha McGaughey', 'software');
insert into Practica1 (nombre, palabraSecreta) values ('Lebbie Writer', 'open system');
insert into Practica1 (nombre, palabraSecreta) values ('Cathrin Chaytor', 'bifurcated');
insert into Practica1 (nombre, palabraSecreta) values ('Kori Baudon', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Leona Danes', 'process improvement');
insert into Practica1 (nombre, palabraSecreta) values ('Boigie Benoiton', 'Devolved');
insert into Practica1 (nombre, palabraSecreta) values ('Mel Tofpik', 'leverage');
insert into Practica1 (nombre, palabraSecreta) values ('Joly Denning', 'bi-directional');
insert into Practica1 (nombre, palabraSecreta) values ('Mead Woolf', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Nanci Red', 'Programmable');
insert into Practica1 (nombre, palabraSecreta) values ('Helyn Quest', 'hardware');
insert into Practica1 (nombre, palabraSecreta) values ('Conni Bradbrook', 'Total');
insert into Practica1 (nombre, palabraSecreta) values ('Darrel Wankel', 'tertiary');
insert into Practica1 (nombre, palabraSecreta) values ('Poul Merrill', 'encoding');
insert into Practica1 (nombre, palabraSecreta) values ('Bella Tappington', 'radical');
insert into Practica1 (nombre, palabraSecreta) values ('Jemmy Strettell', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Margaret Stutte', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Melicent Tomblin', 'help-desk');
insert into Practica1 (nombre, palabraSecreta) values ('Michele Westwater', 'optimizing');
insert into Practica1 (nombre, palabraSecreta) values ('Cyndie Meadowcroft', 'neutral');
insert into Practica1 (nombre, palabraSecreta) values ('Nanny Thickens', 'Progressive');
insert into Practica1 (nombre, palabraSecreta) values ('Joan Beet', 'Re-engineered');
insert into Practica1 (nombre, palabraSecreta) values ('Ramona Aucott', 'application');
insert into Practica1 (nombre, palabraSecreta) values ('Jodee Deabill', 'motivating');
insert into Practica1 (nombre, palabraSecreta) values ('Hyatt Pietruszewicz', 'homogeneous');
insert into Practica1 (nombre, palabraSecreta) values ('Hymie Pund', 'projection');
insert into Practica1 (nombre, palabraSecreta) values ('Shellie Tyne', 'product');
insert into Practica1 (nombre, palabraSecreta) values ('Clareta Satterley', 'function');
insert into Practica1 (nombre, palabraSecreta) values ('Randie Huckleby', 'client-server');
insert into Practica1 (nombre, palabraSecreta) values ('Petr Hearthfield', 'multi-tasking');
insert into Practica1 (nombre, palabraSecreta) values ('Allix Rubinovici', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Vanya Tune', 'Realigned');
insert into Practica1 (nombre, palabraSecreta) values ('Patric Cape', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Edgar Reavell', 'Balanced');
insert into Practica1 (nombre, palabraSecreta) values ('Joane Fareweather', 'installation');
insert into Practica1 (nombre, palabraSecreta) values ('Derk Tejero', 'zero tolerance');
insert into Practica1 (nombre, palabraSecreta) values ('Jules Ryce', 'Function-based');
insert into Practica1 (nombre, palabraSecreta) values ('Maury Gerwood', 'internet solution');
insert into Practica1 (nombre, palabraSecreta) values ('Josh Grunson', 'product');
insert into Practica1 (nombre, palabraSecreta) values ('Alejandrina Beckett', 'Implemented');
insert into Practica1 (nombre, palabraSecreta) values ('Perice Richichi', 'budgetary management');
insert into Practica1 (nombre, palabraSecreta) values ('Fanchon Keith', 'web-enabled');
insert into Practica1 (nombre, palabraSecreta) values ('Foster Basill', 'Visionary');
insert into Practica1 (nombre, palabraSecreta) values ('Linnea Biggin', '24 hour');
insert into Practica1 (nombre, palabraSecreta) values ('Ad Pears', 'Phased');
insert into Practica1 (nombre, palabraSecreta) values ('Norma La Padula', 'bottom-line');
insert into Practica1 (nombre, palabraSecreta) values ('Caril Beer', 'middleware');
insert into Practica1 (nombre, palabraSecreta) values ('Chilton Joblin', 'Self-enabling');
insert into Practica1 (nombre, palabraSecreta) values ('Melita Postins', 'complexity');
insert into Practica1 (nombre, palabraSecreta) values ('Jolie Foulsham', 'Digitized');
insert into Practica1 (nombre, palabraSecreta) values ('Matty Sygrove', 'approach');
insert into Practica1 (nombre, palabraSecreta) values ('Wilden Pochon', 'migration');
insert into Practica1 (nombre, palabraSecreta) values ('Mallissa Logue', 'Organized');
insert into Practica1 (nombre, palabraSecreta) values ('Alford Murrock', 'attitude');
insert into Practica1 (nombre, palabraSecreta) values ('Sybil Gopsell', 'encompassing');
insert into Practica1 (nombre, palabraSecreta) values ('Loy MacAnulty', 'holistic');
insert into Practica1 (nombre, palabraSecreta) values ('Jasun Mertgen', 'didactic');
insert into Practica1 (nombre, palabraSecreta) values ('Bibbie Sadd', 'emulation');
insert into Practica1 (nombre, palabraSecreta) values ('Mano Pllu', 'analyzing');
insert into Practica1 (nombre, palabraSecreta) values ('Devin Causier', 'zero defect');
insert into Practica1 (nombre, palabraSecreta) values ('Florida Whitehurst', 'info-mediaries');
insert into Practica1 (nombre, palabraSecreta) values ('Shoshanna Ullrich', 'maximized');
insert into Practica1 (nombre, palabraSecreta) values ('Reg Trivett', 'content-based');
insert into Practica1 (nombre, palabraSecreta) values ('Xenos Willingham', 'demand-driven');
insert into Practica1 (nombre, palabraSecreta) values ('Phillipe Vertey', '24/7');
insert into Practica1 (nombre, palabraSecreta) values ('Jeanna Millthorpe', 'Future-proofed');
insert into Practica1 (nombre, palabraSecreta) values ('Eadith Simonassi', 'knowledge user');
insert into Practica1 (nombre, palabraSecreta) values ('Margot Meffan', 'Configurable');
insert into Practica1 (nombre, palabraSecreta) values ('Weston Raw', 'full-range');
insert into Practica1 (nombre, palabraSecreta) values ('Yanaton Cadwaladr', 'Compatible');
insert into Practica1 (nombre, palabraSecreta) values ('Rosamond Keig', 'array');
insert into Practica1 (nombre, palabraSecreta) values ('Kary Prothero', 'next generation');
insert into Practica1 (nombre, palabraSecreta) values ('Derrick Hutson', 'value-added');
insert into Practica1 (nombre, palabraSecreta) values ('Ludwig Diano', 'Face to face');
insert into Practica1 (nombre, palabraSecreta) values ('Hyacintha Barracks', 'Persistent');
insert into Practica1 (nombre, palabraSecreta) values ('Ivonne Isitt', 'benchmark');
insert into Practica1 (nombre, palabraSecreta) values ('Constanta Bengtsen', 'Horizontal');
insert into Practica1 (nombre, palabraSecreta) values ('Jacinthe Hellmore', 'concept');
insert into Practica1 (nombre, palabraSecreta) values ('Faustina Dreghorn', 'Public-key');
insert into Practica1 (nombre, palabraSecreta) values ('Bertram Billion', 'Fundamental');
insert into Practica1 (nombre, palabraSecreta) values ('Tonya MacParlan', 'exuding');
insert into Practica1 (nombre, palabraSecreta) values ('Bobette Jilliss', 'Decentralized');
insert into Practica1 (nombre, palabraSecreta) values ('Bertrando Ivetts', 'well-modulated');
